### ISSUE TITLE
Release Schedule for v4.4.5 and v4.5.0

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/LTS#102]
Hey All, I'd like to toss some dates around for upcoming LTS release to see if everyone is on the same page.

Are people open to 

**v4.4.5** released on Tuesday May 24th (with a release candidate next Tuesday May 17th)

**v4.5.0** released on Tuesday June 14th (with a series of release candidates starting Tuesday May 31st)

edit: corrected date for v4.5.0

**Comment by Fishrock123** [comment]
@TheAlphaNerd Why's v4.5.0 so far out? With this OpenSSL release schedule that may run into a security release again.

**Comment by richardlau** [comment]
@TheAlphaNerd Presumably you mean Tuesday June (not July) 14th?

**Comment by TheAlphaNerd** [comment]
@richardlau indeed. Good eye!

**Comment by jasnell** [comment]
That schedule looks fine for me. If there happens to be another OpenSSL release in that time we can deal with it then.

**Comment by mhdawson** [comment]
Looks good to me.

**Comment by Fishrock123** [comment]
I'm not comfortable with it. I'd like to ensure we can get a v4.5.0 out when we plan to.

@TheAlphaNerd Any idea what minors are scheduled so far for that?

**Comment by TheAlphaNerd** [comment]
minors agreed upon:
* https://github.com/nodejs/node/pull/5527
* https://github.com/nodejs/node/pull/5745 (or some variation)
* https://github.com/nodejs/node/pull/1491

minors with lts-watch flag but not discussed:
* https://github.com/nodejs/node/pull/5958
* https://github.com/nodejs/node/pull/6090
* https://github.com/nodejs/node/pull/6404

@Fishrock123 I'm unsure how to do an extended RC on a minor and not run the risk of a security fix pushing it off. How do you think we could better approach it?

**Comment by Fishrock123** [comment]
@TheAlphaNerd Should we just do RC's sooner? Do we need a second staging branch? I'm not sure. People have been waiting quite a few months for some of those and I'd hate to see it delayed again because of a semi-scheduled OpenSSL release-y thing again. :(

Remember we are already significantly behind the schedule we original had discussed for it, aka alongside v6.

If you need any help doing that, I should be able to jump it..

**Comment by Fishrock123** [comment]
Also https://github.com/nodejs/node/pull/6404 probably doesn't need to be backported, one can just access the `_connecting` property.

Aside, i'd love to be able to land https://github.com/nodejs/LTS/issues/108 in it, but that may be too short. Although by that time it will be almost 2 months anyways.

**Comment by TheAlphaNerd** [comment]
@Fishrock123 I can get an RC out next week soon after the v4.4.5 release, no objections regarding #108, wrote in the thread

**Comment by TheAlphaNerd** [comment]
I'm going to close this for now and open a new thread about release cadance
