### ISSUE TITLE
Need lts-watch-v6.x tag

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#103]
Comment says it all.   This is an FYI will see if I can create one

**Comment by mhdawson** [comment]
Ok found how I can create label, just want confirmation from other lts members and then I'll go ahead and create.

@nodejs/lts

**Comment by jasnell** [comment]
Hmm.. given that v6 isn't in LTS yet this may be premature. We do have the
land-on-v6 currently.

**Comment by mhdawson** [comment]
ok good point, I had used land-on-v6 but then remembered for 4.x we use the lts watch and jumped the gun here.  Will just set land-on-v6, closing

**Comment by Fishrock123** [comment]
We don't even need `land-on-v6.x` yet and it really should be removed.

**Comment by Fishrock123** [comment]
Keep in mind that everything lands in Current unless otherwise marked.
