### ISSUE TITLE
2016-05-16 - LTS Meeting Agenda

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#106]
## Invited

@nodejs/lts 

## When

2016-05-16 1:00 PM Pacific Time

### nodejs/LTS

* discuss what to call EOL maintenance period of "Current" release lines [#101](https://github.com/nodejs/LTS/issues/101)

## Participation

Google Hangout on Air link will be posted before the call.

**Comment by jasnell** [comment]
Light agenda. My vote would be to skip. We have no pressing issues.

**Comment by TheAlphaNerd** [comment]
+1

Would like people to chime in on https://github.com/nodejs/LTS/issues/102 if they can

**Comment by jasnell** [comment]
@nodejs/lts ... last call, if there are no further responses I'm going to cancel todays call.

**Comment by mhdawson** [comment]
Would be good to get some discussion on #101 but can probably wait until the next meeting of push forward through github so I'm ok to cancel.

**Comment by jasnell** [comment]
I'm going to call it then. 
Cancelling for today. Let's look to meet up next week.

**Comment by Fishrock123** [comment]
Awesome. :+1:
