### ISSUE TITLE
Discuss backporting `HandleWrap#hasRef()` in a Minor

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/LTS#108]
Bah, I assume this would have been much easier if I'd not mucked up the API.
It's possible we can squash it down into less commits for a backport.

I'd like to see this since it would be useful to have this information in LTS for tooling. It's far less desirable to have to float this patch or patch in `_unrefed` for APIs that don't have it (e.g. `child_process`, whereas net and timers have this.)

This will be even more prevalent if/once anything from `AsyncWrap` gets backported, or even with it's existing API. Specifically, there is no way to tell if a handle will or will not keep the process open without this.

It presents next-to zero risk as far as I can tell. Below is the full commit chain.
- https://github.com/nodejs/node/commit/7d8882ba9a8cfc8f0e2126deb3f3df7456de0ffa https://github.com/nodejs/node/pull/5834
- https://github.com/nodejs/node/commit/f938ef7492f40a81ca2bcae68fd42b8e15235fab https://github.com/nodejs/node/pull/6129
- https://github.com/nodejs/node/commit/9bb5a5e2a127010807f5b8a8bf4cf34109271c55 https://github.com/nodejs/node/pull/6204
- https://github.com/nodejs/node/commit/cad1a62d325b011887349687962700dfe7510525 https://github.com/nodejs/node/pull/6395
- https://github.com/nodejs/node/commit/a58d4839af6dfcb493ead8771cbff21b5ef9f18d https://github.com/nodejs/node/pull/6395
- https://github.com/nodejs/node/commit/428240519c3da4c9f75ef47e2259cfc7b33d5c4d https://github.com/nodejs/node/pull/6395
- https://github.com/nodejs/node/commit/96a9439fd2c9577a735d6abf01990b45b836fba2 https://github.com/nodejs/node/pull/6546
- https://github.com/nodejs/node/commit/fe4837afcc17566a44a7744fb77c195e7b3bf2fd https://github.com/nodejs/node/pull/6546
- Semi-depends-on https://github.com/nodejs/node/commit/2c480bdae67f333e888a6fd8b25425d8b3b50ff0 https://github.com/nodejs/node/pull/6105

cc @TheAlphaNerd

**Comment by TheAlphaNerd** [comment]
@Fishrock123 I'm up for landing these into staging next week and putting them into the rc to see if there are any problems

/cc @nodejs/lts @nodejs/ctc

**Comment by rvagg** [comment]
> It presents next-to zero risk as far as I can tell. Below is the full commit chain.

The risk that backporting seemly non-risky changes is directly proportional to the delta between the branches involved. Simply _doing_ the backport puts us at risk of getting things wrong and then there's the surrounding structures which may have become important for the operation of a feature without noticing and they may not be present in the older branch.

I think we'd need to see a PR for it along with a CI run and then we can make a judgement on the code. If it's particularly difficult to backport just to have a discussion then that goes back to my above point about risk.

**Comment by jasnell** [comment]
+1 to everything @rvagg said. As the delta between master and v4 grows, we
need to become more conservative about the things we cherry pick vs
backport using a reviewed PR and need to get CI/CITGM runs going more
often. Our intuition that things "shouldn't" break is not enough of a
guarantee.

**Comment by Fishrock123** [comment]
Well, I don't think I need this info on v4 in the short term anyways, so I'm willing to drop it.

**Comment by TheAlphaNerd** [comment]
@Fishrock123 with v6 coming up for LTS soon I think we should consider not landing this on v4. Thoughts?

**Comment by Fishrock123** [comment]
¯\\\_(ツ)\_/¯

may be useful if all of async_wrap gets backported

**Comment by TheAlphaNerd** [comment]
@Fishrock123 do you still want to pursue this for v4?

**Comment by Fishrock123** [comment]
nah
