### ISSUE TITLE
Track backport of v8_inspector

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/LTS#109]
This issue is to track all commits that will be needed to track the backport of https://github.com/nodejs/node/pull/6792

Other PR's that will need to be backported too

https://github.com/nodejs/node/pull/7070
https://github.com/nodejs/node/pull/7078
https://github.com/nodejs/node/pull/7118
https://github.com/nodejs/node/pull/7212
https://github.com/nodejs/node/pull/7228
https://github.com/nodejs/node/pull/7232
https://github.com/nodejs/node/pull/7248
https://github.com/nodejs/node/pull/7258

Should we make a temporary label to track these issues?

/cc @ofrobots

**Comment by Fishrock123** [comment]
The inspector seems awfully large for a backport, are we _sure_ we want to be doing this?

What will our messaging look like? This is a very sizable feature. Doesn't feel very lts-y at all.

**Comment by ofrobots** [comment]
v6.x is not LTS yet. I think this issue is necessary at this point. We should track inspector support like everything else we merge into Current.

**Comment by TheAlphaNerd** [comment]
@ofrobots I've gone through and updated the top comment with all landed PR's that have the `v8_inspector` label. Let me know if you think I've missed anything

@rvagg I've also gone ahead and added all of these PR's to the v7 milestone. Please let me know if you prefer them not to be added

**Comment by rvagg** [comment]
Well I don't _think_ we're going to need to do any backporting other than master -> v6.x but having a list of commits might be helpful if we end up having to back it out prior to v6 LTS for whatever reason.

**Comment by TheAlphaNerd** [comment]
everything has been backported
