### ISSUE TITLE
Release schedule for v4.4.6, v4.4.7, and v4.5.0

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/LTS#114]
`v4.4.6` Thursday June 22nd
 * contains only security updates.

`v4.4.7` Tuesday June 28th
 * contains a variety of patch's that have been blocked by the security update
 * Fixes #112 

`v4.5.0` Tentatively July 19th with a 2 week R.C. cycle beginning July 5th

If anyone has suggestions for a different release cycle please let me know.

/cc @nodejs/release

**Comment by jasnell** [comment]
No objections to this schedule

**Comment by Fishrock123** [comment]
@TheAlphaNerd have you started on v4.5.0 RCs yet?

**Comment by TheAlphaNerd** [comment]
Not yet. I was waiting for a few of the buffer commits to come in and was a
bit distracted by life this week. Will be aiming to get something out next
week.

**Comment by rvagg** [comment]
Do we have an updated schedule @TheAlphaNerd? the queue is pretty large atm for a patch, 217 commits waiting on staging.

**Comment by TheAlphaNerd** [comment]
I'm planning an rc for tomorrow. 😊
