### ISSUE TITLE
LTS WG meeting 27 June 2016

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#116]
# Invited

@nodejs/lts 

# Participation

Hangout on Air for Participants: https://hangouts.google.com/hangouts/_/hoaevent/AP36tYeGFi6J9adOYlog07FUdg24tc2CvWDwxRBwsiW01hW8mjTeGg?hl=en&authuser=0

For Observers: http://www.youtube.com/watch?v=PQzWcFAdyuM

Minutes: https://docs.google.com/document/d/1gtLreR_GDcrGc6g2hHTsYycVA--UlwKuUv8vqtk-cDw/edit?usp=sharing

# Agenda

**Comment by ofrobots** [comment]
For the next time could we have advance notice/warning? https://github.com/nodejs/LTS/issues/111 needs to be discussed at an LTS meeting, but unless there is a plan ahead of time, it difficult for someone in Europe (@natorion) to be able to join at 10pm in the evening.

https://github.com/nodejs/LTS/issues/111#issuecomment-228595387 from @natorion:
> I would gladly try to join the next meeting. When is it scheduled?

**Comment by TheAlphaNerd** [comment]
s/July/June in title

**Comment by TheAlphaNerd** [comment]
I would like to discuss https://github.com/nodejs/LTS/issues/114 briefly and some citgm updates

**Comment by mhdawson** [comment]
PR for minutes https://github.com/nodejs/LTS/pull/117/files @nodejs/lts

**Comment by TheAlphaNerd** [comment]
great meeting!
