### ISSUE TITLE
Codename for Node.js v6 LTS

### ISSUE THREAD

**Issue by rvagg** [nodejs/LTS#118]
It's time to start working toward assigning a codename to v6 LTS! My proposal is that @nodejs/lts narrows down the list to 3 if we can, then post it to a locked thread in https://github.com/nodejs/ctc so that only Collaborators can comment, we put a comment per name and invite collaborators to vote by pinning an emoji to one of the comments.

Here's the candidate list, thanks to http://www.periodni.com/elements_symbols_sorted_alphabetically.html

---

**Barium**

> Barium was discovered by Sir Humphry Davy (GB) in 1808. The origin of the name comes from the Greek word barys meaning heavy. It is a soft, slightly malleable, silvery-white metal. Barium oxidises in air and reacts with water. Soluble compounds are toxic by ingestion. Barium is found in barytine (BaSO4) and witherite (BaCO3), it is never found in pure form due to its reactivity. Barium must be stored under kerosene to remain pure. Barite, or barium sulfate (BaSO4) is used as a filter for rubber, plastics and resins. It is insoluble in water and so is used in X-rays of the digestive system. Barium nitrate, Ba(NO3)2, burns brilliant green and is used in fireworks. The price of 99.2 % pure barium pieces is 1347.20 € for 1000 g.

**Berkelium**

> Berkelium was discovered by Stanley G. Thompson, Albert Ghiorso, and Glenn T. Seaborg (US) in 1949. Named after Berkeley, a city in California, home of the University of California, USA. It is synthetic radioactive metal. Berkelium was made by bombarding americium with alpha particles. 

**Beryllium**

> Beryllium was discovered by Louis-Nicholas Vauquelin (FR) in 1798. The origin of the name comes from the Greek word beryllos meaning mineral beryl; also called glucinium from the Greek word glykys meaning sweet. It is a steel-grey metal resistant to attack by concentrated nitric acid. It has excellent thermal conductivity and is nonmagnetic. At ordinary temperatures, it resists oxidation in air. Beryllium and its salts are toxic and should be handled with the greatest of care. Beryllium is found mostly in minerals like beryl [AlBe3(Si6O18)] and chrysoberyl (Al2BeO4). Pure beryllium is obtained by chemically reducing beryl mineral and by electrolysis of beryllium chloride. Its ability to absorb large amounts of heat makes it useful in spacecrafts, missiles, aircrafts, etc. Emeralds are beryl crystals with chromium traces giving them their green colour. The price of 99.5 % pure beryllium lump is 200.70 € for 50 g.

**Bismuth**

> Bismuth was discovered by Basil Valentine (DE) in 1450. The origin of the name comes from the German words Weisse Masse meaning white mass; now spelled wismut and bisemutum. It is a hard, brittle, steel-grey metal with a pink tint. It is stable in oxygen and water but dissolves in concentrated nitric acid. Bismuth can be found free in nature and in minerals like bismuthine (Bi2S3) and in bismuth ochre (Bi2O3) Main use is in pharmaceuticals and low melting point alloys used as fuses. The price of 99.99 % pure bismuth pieces is 110.20 € for 1000 g.

**Bohrium**

> Bohrium was discovered by Peter Armbruster, Gottfried Münzenber (DE) and their co-workers at the Heavy Ion Research Laboratory (Gesellschaft für Schwerionenforschung, GSI) in Darmstadt, Germany in 1981. Named in honour of Niels Bohr, the Danish physicist. It is a synthetic radioactive metal. Bohrium was produced by bombarding bismuth-204 with chromium-54. 

**Boron**

> Boron compounds have been known for thousands of years, but the element was not discovered until 1808 by Sir Humphry Davy (GB) and independently by Joseph-Louis Gay-Lussac and Louis-Jaques Thénard (FR). The origin of the name comes from the Arabic word buraq and the Persian word burah meaning boraks (Na2B4O7*10H2O). It is hard, brittle, lustrous black semimetal. Boron is unreactive with oxygen, water, alkalis or acids. It combines with most metals to form borides. Boron is obtained from kernite, a kind of borax (Na2B4O7.10H2O). High purity boron is produced by electrolysis of molten potassium fluroborate and potassium chloride (KCl). Amorphous boron is used in pyrotechnic flares to provide a distinctive green colour and in rockets as an igniter. The price of 99.5 % pure boron pieces is 997.90 € for 250 g.

**Bromine**

> Bromine was discovered by Antoine-Jérôme Balard (FR) in 1826. The origin of the name comes from the Greek word bromos meaning stench. It is a reddish-brown liquid with suffocating, irritating fumes that gives off poisonous vapour. It is a oxidizer that causes severe burns. Bromine occurs in compounds in sea water. It was once used in large quantities to make a compound that removed lead compound build up in engines burning leaded gasoline. Now it is primarily used in dyes, disinfectants and photographic chemicals. The price of 99.8 % pure bromine liquid is 79.10 € for 1000 g.

---

For me, the only one I'd easily strike is Bromine because of the meaning ("stench"). Berkelium, Beryllium and Bohrium all have slight problems with ease spelling from sound, but I have a soft spot for Bohrium because it was named after Bohr. Boron might trigger associations with "boring", but meh.

**Comment by Fishrock123** [comment]
Picking up from the conversations after last year's initial LTS, is there a good reason for keeping it? Why not just drop it and have `lts = true`?

**Comment by jasnell** [comment]
I'd go with either Barium or Bohrium, the former being my favorite. Barium
is highly reactive and is never found naturally in a pure form. This fits
well with Node.js' small core philosophy in that it's always Node.js plus
something more when found in the wild. Barium is also quite versatile.

**Comment by TheAlphaNerd** [comment]
Beryllium is a pretty nice one too, considering it is found in emerald (the node js stone)

**Comment by Starefossen** [comment]
> Picking up from the conversations after last year's initial LTS, is there a good reason for keeping a name? Why not just drop it and have `lts = true`?

From a Docker point of view the LTS code words are great since they uniquely refers to one specific LTS version and can be referenced like this:

```docker
FROM node:argon

...
```

**Comment by jasnell** [comment]
At this point I'm definitely +1 on keeping the code name. Yes it can be a bit silly but there are folks who have found good uses for it.

**Comment by rvagg** [comment]
My recollection of the previous discussion around codenames is that we'd stick with it for now and give it a proper trial because we figured it would become more valuable when we have >1 LTS line out there. I'm still a big fan, mainly for the practical benefits but also partly to add a tiny bit of fun into the whole process.

So let's try and approach it this way: which ones would you knock out and for what reason?

* Barium
* Berkelium
* Beryllium
* Bismuth
* Bohrium
* Boron
* Bromine

Strong -1 on Bromine from me because of the origin meaning.

-0 on Berkelium and Beryllium for slight difficulty in reading and spelling, I'd say the same to Bohrium but I like it for other reasons.

Also, I know @cjihrig has opinions here, he spoke about this @ https://youtu.be/kn0Trjl7ZRE?t=17m51s and said Boron would be a good choice because of the ease of spelling for non-native english speakers.

**Comment by TheAlphaNerd** [comment]
That's a really interesting point 

Based on that I'm in favor of boron..

**Comment by Fishrock123** [comment]
> My recollection of the previous discussion around codenames is that we'd stick with it for now and give it a proper trial

I have a very strong recollection of that only being for **the** first KLTS, aka _only_ v4 LTS.

---

Please see last year's discussion: https://github.com/nodejs/LTS/issues/26 -- discussed at https://github.com/nodejs/LTS/issues/43 (recording, since there were no good minutes taken: https://youtu.be/wfg2nHXAQqI?t=8m15s)

Going to loop in the people who didn't really (or seem to) like the idea last year:
@zkat, @aredridel, @isaacs, @thomblake

**Comment by Fishrock123** [comment]
Going to also loop in something that @brycebaril said to me, which is quite relevant for us (NodeSource): 

> the naming is very helpful for us, prevents us from having to have two version numbers in our product name based on Node, e.g.
> N|Solid 0.0.0 Argon and N|Solid 0.0.0 Beryllium
vs.
N|Solid 0.0.0 (Node.js v4) and N|Solid 0.0.0 (Node.js v6)

**Comment by aredridel** [comment]
Still doesn't seem to convey anything to me. "v6 LTS" says what it is, "Boron" is a conversation on "what does that mean? Oh. It's v6 LTS."

**Comment by DrEVILish** [comment]
Android Kitkat tells you the same level of information as Node Boron.
I for one am in favour of the short easy to say names periodic table elements for each letter i.e Carbon, Diamond instead of Darmstadtium Dubnium Dysprosium as I feel they wouldn't translate well.

**Comment by rvagg** [comment]
From our [README](https://github.com/nodejs/LTS/), which we've been using as our policy document:

> All LTS releases will be assigned a "codename" drawn from the names of elements on the Periodic Table of Elements. For each upcoming LTS release, the LTS Working Group will select a handful of candidate names and submit those for a collaborator vote.

This was done when we changed it from our "proposed" to "current" plan on the 23rd of July 2015.

I can't find any official vote on this matter. I believe it's something that was floated, got fairly enthusiastic reception both on nodejs/node and on this repo and then we received the objections from npm at the last minute before we shipped v4, as per the video @Fishrock123 linked to we decided to move on "for this release" from the objections. The closest thing for a way forward after shipping is this from @Fishrock123 @ https://github.com/nodejs/LTS/issues/26#issuecomment-146070425:

> We can re-evaluate if it was useful or not for the second LTS.

And as with everything we do, it's open for discussion and we can do that now if folks feel strongly enough, but you'd better start making a good case for a policy change otherwise we'll have to move forward with what we have in place.

**Comment by jasnell** [comment]
See: https://github.com/nodejs/node/issues/8026 for the voting thread.

**Comment by Starefossen** [comment]
Since I can not comment on #127, I am posting this here.

I would like the LTS wg to take into consideration that LTS code names are very useful for the official Node.js Docker Image. Since there are multiple LTS versions and they change from time to time we do not have a tag named `lts`, instead we use the LTS code name to refer to LTS versions (in addition to normal version numbers).

[A GitHub code search for `node:argon`](https://github.com/search?l=dockerfile&q=node%3Aargon&type=Code&utf8=%E2%9C%93) yields 1,140 public Dockerfiles using using `argon` variants as a base image.

**Comment by jasnell** [comment]
Sorry @Starefossen ... that was my bad... #127 shouldn't have been locked.

**Comment by TheAlphaNerd** [comment]
We got there!
