### ISSUE TITLE
LTS WG meeting 13 July 2016

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/LTS#119]
# Invited

@nodejs/lts @natorion @fhinkel 

# Time

1pm UTC July 13 or in your local timezone

# Participation

Hangout on Air for Participants: https://hangouts.google.com/hangouts/_/hoaevent/AP36tYeo_lzacGF9ULIABC7XQXsUGRchNTCX3-w0BmI9I5DxZ2iCPQ?eid=100598160817214911030&hl=en&authuser=0

For Observers: http://www.youtube.com/watch?v=ye3auVn41Z4

Event page: https://plus.google.com/events/c5e7mth9m0r84icbvp987uni9is

# Agenda

### nodejs/LTS

Managing floating V8 patches: https://github.com/nodejs/LTS/issues/111
Semver-Minor commits in v4.x-staging  https://github.com/nodejs/LTS/issues/120 https://github.com/nodejs/LTS/issues/120

### nodejs/node

build: export openssl symbols on windows (v4.x) https://github.com/nodejs/node/pull/7676

**Comment by fhinkel** [comment]
Thanks!

**Comment by mhdawson** [comment]
Updated hangout links with new meeting hosted by node.js

**Comment by natorion** [comment]
Let's get this started!

**Comment by mhdawson** [comment]
Link for minutes: https://docs.google.com/document/d/1XcnfN1RhsDVX8y4dzYRciApsCZMLfzNzctLa0cLdw_w/edit

**Comment by mhdawson** [comment]
correct link https://hangouts.google.com/hangouts/_/hoaevent/AP36tYeo_lzacGF9ULIABC7XQXsUGRchNTCX3-w0BmI9I5DxZ2iCPQ?eid=100598160817214911030&hl=en&authuser=0

**Comment by mhdawson** [comment]
PR for minutes https://github.com/nodejs/LTS/pull/122
