### ISSUE TITLE
Semver-Minor commits in v4.x-staging

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/LTS#120]
# Agreed upon
> reference included when not found in original discussion

**Buffer Api**
* [[`b4a279155a`](https://github.com/nodejs/node/commit/b4a279155a)] - **(SEMVER-MINOR)** **buffer**: backport new buffer constructor APIs to v4.x (Сковорода Никита Андреевич) [#7562](https://github.com/nodejs/node/pull/7562)
* [[`ee2f08fe51`](https://github.com/nodejs/node/commit/ee2f08fe51)] - **(SEMVER-MINOR)** **buffer**: ignore negative allocation lengths (Anna Henningsen) [#7562](https://github.com/nodejs/node/pull/7562)

**Buffer Zero Fill Backport**:
* [[`a27eeab6a5`](https://github.com/nodejs/node/commit/a27eeab6a5)] - **(SEMVER-MINOR)** **buffer**: backport --zero-fill-buffers cli option (James M Snell) [#5745](https://github.com/nodejs/node/pull/5745)

**intel v-tune profiling**:
* [[`cc8ec23ad5`](https://github.com/nodejs/node/commit/cc8ec23ad5)] - **(SEMVER-MINOR)** **build,src**: add Intel Vtune profiling support (Chunyang Dai) [#5527](https://github.com/nodejs/node/pull/5527)
  -  [ref][1]

**V8 test runner**:
* [[`c6fab003b6`](https://github.com/nodejs/node/commit/c6fab003b6)] - **(SEMVER-MINOR)** **deps**: backport 9c927d0f01 from V8 upstream (Myles Borins) [#7451](https://github.com/nodejs/node/pull/7451)
* [[`5f9110e231`](https://github.com/nodejs/node/commit/5f9110e231)] - **(SEMVER-MINOR)** **test**: run v8 tests from node tree (Bryon Leung) [#4704](https://github.com/nodejs/node/pull/4704)

**V8 post mortem data**:
* [[`7652f559bd`](https://github.com/nodejs/node/commit/7652f559bd)] - **(SEMVER-MINOR)** **deps**: cherry-pick 68e89fb from v8's upstream (Fedor Indutny) [#3779](https://github.com/nodejs/node/pull/3779)

# Not Agree Upon

**Repl tab copy fix**:
* [[`1aa9c318c9`](https://github.com/nodejs/node/commit/1aa9c318c9)] - **(SEMVER-MINOR)** **repl**: copying tabs shouldn't trigger completion (Eugene Obrezkov) [#5958](https://github.com/nodejs/node/pull/5958)

**Fix Linking for shared library**:
* [[`2e4fb99a86`](https://github.com/nodejs/node/commit/2e4fb99a86)] - **(SEMVER-MINOR)** **src**: add node::FreeEnvironment public API (Cheng Zhao) [#3098](https://github.com/nodejs/node/pull/3098)

[1]: https://github.com/nodejs/LTS/issues/102#issuecomment-219546056

**Comment by TheAlphaNerd** [comment]
As a note, while I was reviewing commits today I opted to land a handful of semver minor commits into v4.x-staging that had not yet been voted on by the CTC or WG that seemed like decent candidates for the `v4.5.0` release. The intention was to audit these as part of the RC release, but in retrospect that was not done in a very transparent way. In future I will tag semver minors for a working group discussion before landing in staging.

**Comment by bnoordhuis** [comment]
The V8 test runner changes can be semver-patch.

I'm okay with landing the node::FreeEnvironment() change.  I'd be in favor (as opposed to just okay) if I knew there would be actual users.  Electron doesn't use v4.x.

**Comment by TheAlphaNerd** [comment]
In today's LTS WG meeting we discussed all commits on the list. There was consensus that all of the commits mentioned in the post are appropriate for LTS and should be landed in v4.5.0.

I am closing this issue but please feel free to continue the conversation if you have any questions or concerns
