### ISSUE TITLE
Work with TypeScript team to get canonical node libraries

### ISSUE THREAD

**Issue by clavecoder** [nodejs/LTS#123]
The TypesScript team has been encouraged, Microsoft/TypeScript#9466, to support/maintain `node` as a built in library, much like `lib.d.ts`. Could someone from the NodeJS Foundation make overtures to the TypeScript team to work out a way for them to support a canonical `node.d.ts` declaration? With the imminent release of **Angular 2** and the advent of **Universal JavaScript**, both TypeScript and NodeJS have become critical tools for the JavaScript community. It would be great if they worked well together.

My [similar sentiments](https://github.com/Microsoft/TypeScript/issues/9466#issuecomment-232550130) to the TypeScript team.

**Comment by rvagg** [comment]
As far as I'm aware we have no TypeScript aficionados around here so I'm not sure there's a whole lot we can do. I understand that TypeScript is becoming more (not less, much to the surprise of many, including myself) interesting to developers so it's something we should at least be paying attention to and helping if we can but I really don't see anything we can do without either input from the TypeScript folks or having Node TypeScript community folks working on it from here.

Pulling in @nebrius and @joshgav to this thread, perhaps they would like to connect some Microsoft folks here.

This isn't an LTS concern so this issue doesn't really belong here, I'm inclined to close it but perhaps we can do some quick exploration to see if there's another home for this discussion.

Also, what is "Universal JavaScript" supposed to mean?

**Comment by clavecoder** [comment]
[Universal JavaScript][1], previously Isomorphic JavaScript, (they can be [considered distinct][2]), is a developer experience championed by the ReactJS community and is now encouraged by the AngularJS community. A key component of these experiences is the use of module builders such as Browserify and WebPack to treat browser script like NodeJS by including polyfills for native NodeJS libraries and using `require('module')` as the bundling mechanism for all assets, not just JavaScript modules. It is one reason that the replacement of bower with npm by the community has been accelerated.

Per your request, I will encourage the TypeScript team to reach out to you.


[1]: https://medium.com/@mjackson/universal-javascript-4761051b7ae9#.odi78ce0h
[2]: http://www.2ality.com/2015/08/isomorphic-javascript.html

**Comment by joshgav** [comment]
/cc @danielrosenwasser @bowdenk7

Perhaps this should go in nodejs/ctc?

**Comment by nebrius** [comment]
Agreed, this repo isn't the right place. Let's redirect to nodejs/ctc and continue the conversation there. It's an important one IMO.

**Comment by DanielRosenwasser** [comment]
I think the TypeScript team would definitely be open to having a conversation around this. If you'd prefer to migrate the issue anywhere, definitely loop us in as well.

**Comment by Fishrock123** [comment]
I don't think we'd want it as apart of the standard process, adding extra burden to new contributions would not be good.

The TypeScript team may still need to maintain it at this point, even if it is in an official repo here, since there hasn't been interest form the existing collaborators.


If the main hurt is figuring out what changed between releases, we could probably help with the tooling to figure that out. I think our standard release tooling may be good enough to identify the commits.

**Comment by nojvek** [comment]
Just wondering if an issue in nodejs/ctc has been created?

**Comment by TheAlphaNerd** [comment]
I'm closing this for now. Please feel free to open an issue in nodejs/ctc
