### ISSUE TITLE
LTS Meeting - Aug 22 (Recommend skip)

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#129]
@nodejs/lts --- I don't believe we have any pressing issues and I'm tied up all day with back to school stuff for the kids. Unless anyone has anything super pressing, I recommend skipping this week.

**Comment by Fishrock123** [comment]
skip.

**Comment by mhdawson** [comment]
I'm assuming we are skipping unless I hear otherwise.

**Comment by TheAlphaNerd** [comment]
you don't need to skip it just because I'm in a hot spring
