### ISSUE TITLE
Should we consider swapping the timeframe for Active LTS and Maintenance

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#130]
Perhaps there is even a third category, but I want to avoid getting WAY TOO confusing.

My thoughts here are that now that `v6` is coming into LTS it feels like we should start being a bit more conservative with `v4`.

For the first 6 months we did our best to keep the delta between `v4` and `v5` as small as possible. During `v6` we still tried to backport at a moderately aggressive pace, but started slowing down as not everything could be moved.

With `v6` moving to LTS I personally feel much more conservative about landing things into the `v4` release stream. Why should we take a risk for any non critical bug on a release stream that is primarily stable. Even a "fix" has the potential to break reliable production code.

I'm not 100% that it makes sense to call the support between Oct -> April of `v4` as Maintenance, as we will likely be back ported non critical bugs... but it still feels like perhaps it is less than active.

Our LTS strategy is already complicated enough for others to Grok, so I don't know if this needs an official title, but I think it may make sense for us as a group to discuss what we think should be done. Adding this to the LTS agenda.

**Comment by jasnell** [comment]
Let's leave things as they are for now and see how the six months overlap with v6 and v4 both being under active LTS goes. If it proves to be too much work, then we can look at adjusting it.

**Comment by jasnell** [comment]
but, yes, in general, once v6 goes LTS, updates to v4 should start to become far less frequent, I think.

**Comment by MylesBorins** [comment]
Closing this for now... happy with current calendar
