### ISSUE TITLE
LTS Meeting for Today (2016-09-19)

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/LTS#135]
@nodejs/lts, can anyone make it?

there's some stuff to discuss but it isn't particularly urgent: https://github.com/nodejs/LTS/issues?q=is%3Aissue+is%3Aopen+label%3Alts-agenda

**Comment by TheAlphaNerd** [comment]
sorry to be Mia, was airborne. I do think we need to have some discussions
re: who will be the taking the lead on v6

**Comment by jasnell** [comment]
I was also in flight on this so my apologies for missing.

Also, fwiw, I have asked @TheAlphaNerd if he would consider taking the lead for making sure these meetings are regularly scheduled and have documented agendas as I've simply not had the time to adequately keep up on it.

**Comment by TheAlphaNerd** [comment]
closing as the date has passed
