### ISSUE TITLE
LTS codename lists

### ISSUE THREAD

**Issue by ankon** [nodejs/LTS#136]
So, I'm using Node for various things, and on my development machines I prefer to use "latest and greatest". But, for compatibility with other developers who are not as up-to-date our Travis executes the builds for both the current node.js version and ideally the LTS version.

And here comes the problem: It is really hard to figure out what the "LTS version" actually is. From nvm's perspective it is identified by something like "lts/codename" (https://github.com/creationix/nvm#long-term-support), and nvm's documentation points to this repository for the schedule. It mentions one example "argon". But on this repository I cannot find any mentioning of code names in the tables and diagrams -- only if I actually read the 4.2.0 release announcement (https://nodejs.org/en/blog/release/v4.2.0/) does it pop up again: "argon".

Problem here is that the current LTS version on the node.js homepage is 4.5.0, so unless one is intimately familiar with the node.js versioning that 4.2.0 blog doesn't really look like it would be relevant for the discussion.

As long as code-names are used as identifiers that span multiple semver minor versions, could these names be made properly visible on this repository's README please?

(Likely relates to: https://github.com/nodejs/LTS/issues/127 discussing whether such names make sense, and https://github.com/nodejs/LTS/issues/132 for updating the chart)

**Comment by TheAlphaNerd** [comment]
@rvagg is this being included in your readme rewrite?

**Comment by rvagg** [comment]
Yeah, https://github.com/nodejs/LTS/blob/readme-rework/README.md, but I could make a separate column for it. Also now available in JSON form at https://github.com/nodejs/LTS/blob/master/schedule.json

**Comment by ankon** [comment]
A dedicated column would be much appreciated - it simplifies the scanning of the document quite a bit, especially for non-developing ops people that really are not interested in the full details and history, but a definite and explicit answer to the question "how is this called what i need?"
