### ISSUE TITLE
Docment backporting process

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#138]
Currently this is not documented. Let's use this issue to track the process

Steps:
- Branch off of vX.x-staging
- cherry-pick commit(s) to be backported
  - this should include all original meta data
- Make necessary changes to get test suite passing
- Submit PR to vX.x-staging

When landing it is a good idea to include that new PR # as a `Ref:` in the commit meta data

**Comment by MylesBorins** [comment]
Wow this is old and concise

**Comment by sam-github** [comment]
There you go, as easy as 1, 2, 3, 4... the work of an afternoon ;-P
