### ISSUE TITLE
LTS WG Meeting - 2016-10-03 8:00pm UTC

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/LTS#139]
## Invited

@nodejs/lts 
@indutny 
## When

8PM Monday October 3d UTC, or in your local timezone:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20161003T16&p1=179&ah=1
## Where

Hangouts on Air:
- Observers: https://www.youtube.com/watch?v=ccVUaJkCdXY
- Participants: https://hangouts.google.com/call/dtk5pdlwzjdhtkdirrarg3bjwae
### nodejs/LTS
- meta: updated messaging regarding dates [#141](https://github.com/nodejs/LTS/pull/141)
  - Proposal regarding messaging + communication of important LTS dates
  - discussion specific to 0.10 + 0.12 to be tabled until later in the meeting
### nodejs/node
- tls: introduce `secureContext` for `tls.connect` [#4246](https://github.com/nodejs/node/pull/4246)
  - discussion led by @indutny 
- http: 451 status code "Unavailable For Legal Reasons" [#4377](https://github.com/nodejs/node/pull/4377)
- build: introduce configure --shared [#6994](https://github.com/nodejs/node/pull/6994)
### Additional Items
- v6 LTS planning
  - who will be taking lead
  - how to better automate the process
  - specific date of moving to LTS
- v0.10 and v0.12 EOL
  - we need to be 100% on the same page about the EOL dates
  - we need to discuss the result of changing these dates and the types of messaging we should be doing to avoid confusion in the future.
- future v4 release schedule
  - when next patch
  - when next minor
## Minutes

https://docs.google.com/document/d/1Kz-CcClaH-rY8odqBRd72mLmER11xHPnL3vovaogDtU/edit

**Comment by ErisDS** [comment]
At what point does maintenance for 0.10.x officially end? It was supposed to be yesterday, however there have been no notices anywhere, no announcements and I see it's not on the agenda here? 

I've been waiting all weekend for some sort of announcement so we can drop support in Ghost. I have been strongly advocating within the ecosystem that we should all remove 0.10 support from our projects ASAP after Node.js maintenance ends, to reinforce the LTS schedule and, hopefully, build confidence in Node.js as a dependable platform.

**Comment by jasnell** [comment]
Oct 31st is the cutoff for v0.10. The date in the readme table is a typo.
I'm planning on a blog post on the nodejs.org site in about a week.

Also, fwiw v0.12 expires Dec 31st.
v6 will go into LTS the day v7.0.0 is released. Tentatively Oct 25th.

**Comment by ErisDS** [comment]
> The date in the readme table is a typo.

WTAF? 

This date has been there for over a year. This blog post also says "first week of October: https://nodejs.org/en/blog/community/node-v5/. The LTS plan table is linked from pretty much everywhere else, including the [home page](https://nodejs.org/en/) and the [original announcement](https://medium.com/@nodesource/essential-steps-long-term-support-for-node-js-8ecf7514dbd#.utqbife0q).

Ghost's supported version guide (which I've shown to @rvagg) also has had the same date for nearly a year: http://support.ghost.org/supported-node-versions/. Ember just announced their LTS plan, and also expects the same date: http://emberjs.com/blog/2016/09/07/ember-node-lts-support.html

The entire community has been working towards that date, we've been doing marketing around it. I've been advocating the LTS plan, trying to get the ecosystem to rally behind it and now you tell me, without any hint of apology, it's a typo?

Where exactly should I have gone to find that out?

**Comment by jasnell** [comment]
I apologize for any confusion. Regardless of whether v0.10 expires on Oct
1st or the 31st, after October there will be no further updates. In fact,
unless a critical security issue emerges between now and the 31st, I would
not expect any further updates to that release line. The current
recommended baseline is the current active LTS v4.

**Comment by ErisDS** [comment]
Whether or not there is going to be another release is not the point.

The point is that the ecosystem looks to you for leadership. Every discussion about EOL for Node v0.10 anywhere in the entire community for the past year has used the 1st October date because that's what it says on the only official roadmap that there is. It's the only guidance we have had on which to base important decisions and marketing materials for our own user bases.

This is not a minor typo in an unimportant document. This is incompetence that cascades down to every other module, project & product that has based their decision making on that date. Now we all look like incompetent fools as well. 

This is seriously not OK.

It's also not the first time I've run into a serious problem with the communication around the LTS schedule. It really seems to me that the @node.js/LTS group should include people who understand and deal with the marketing & community management side of things?

**Comment by jasnell** [comment]
> the @node.js/LTS group should include people who understand and deal with the marketing & community management side of things?

Additional people in the LTS team would be fantastic and quite welcome.

**Comment by TheAlphaNerd** [comment]
@ErisDS I've added discussion of the v0.10 and v0.12 EOL to our agenda for Monday. Not only will we discuss defining the EOL date, but the resulting confusion of making changes so close to the date itself. If you have the time to join us and discuss the process that would be rad, but I do feel that I can proxy your position effectively.

The document on the LTS site has been updated to reflect our current plan, but we definitely need to improve upon our messaging when these things happen. Following tomorrow's meeting we will prioritize an official blog post that will let people know the important dates coming up in the next couple month's for v0.10, v0.12, and v6

**Comment by stefanpenner** [comment]
> This is not a minor typo in an unimportant document. This is incompetence that cascades down to every other module, project & product that has based their decision making on that date. Now we all look like incompetent fools as well.

Ya this isn't ideal, as we have aligned our own schedules around this. In-fact we have already executed on the node 0.10 EOL as originally documented. Luckily our own 6 week release cycle should buffer this from our users, that is assuming the 0.10.x does in-fact reach EOL on the 31st.

Obviously these processes always needs some refinement, my only request seem to already be covered by @TheAlphaNerd's above comment (preventing future confusion).

**Comment by TheAlphaNerd** [comment]
I've submitted a PR that

**Comment by TheAlphaNerd** [comment]
I've submitted a PR that describes a potential process for determining specific LTS dates that affords us flexibility while still maintaining a reasonable contract with individuals making decisions based on our dates.

https://github.com/nodejs/LTS/pull/141

The PR is going to be the first item on the agenda tomorrow and I would very much like to hear feed back from individuals like @ErisDS, @nathanhammond, and other individuals who have a vested interest in this. If you can join us that would be amazing, but in lieu of that please feel free to post your thoughts regarding the PR above if you have time and I'll bring it up during the discussion.

**Comment by ErisDS** [comment]
I will be there. To clarify the process of joining, I guess the participant link gets shared here nearer the time or is it posted somewhere else?

**Comment by Fishrock123** [comment]
To be clear: it would be advised if you already treat 0.10.47 as the last release. It in highly unlikely there will be another.

I think at this point we're just biting the bullet. We can clarify for future EOL's but I suspect changing this again will only cause more confusion.

> To clarify the process of joining

Just a note, the LTS WG isn't an "officially charted" group, but it acts as a team who do most of the decision work for LTS, with issues going to the CTC to arbitrate if there really is a problem.

I'm not sure there is a process on joining other than "show up if you care", tbqh.

**Comment by ErisDS** [comment]
I was referring (at least for now) to the process of joining this evening's meeting 😉

**Comment by Fishrock123** [comment]
@ErisDS Oh. A google hangouts participant link should be posted in this issue. I think it is open to anyone.

**Comment by rvagg** [comment]
@ErisDS @nathanhammond thankyou both so much for joining us! It's not exciting work being involved in LTS planning and management so it can be hard to get a good group together. It's great to have people with opinions to offer and who are real downstream stakeholders of the efforts being done here. Please feel free to join in on future meetings, as often as you like, and you're also welcome to join the working group (which I believe @ErisDS has already said she'd like to do?) more formally and be involved in the decision-making process.

**Comment by ErisDS** [comment]
I'm in 👍  As I said to @TheAlphaNerd, I will try to be at meetings as often as possible, so please let me know if there are tasks which can be delegated to me.
