### ISSUE TITLE
npm LTS

### ISSUE THREAD

**Issue by rvagg** [nodejs/LTS#14]
Following up from @zkat's comment in the summit repo about npm 2.x LTS: https://github.com/nodejs/summit/issues/1#issuecomment-117736102 we should pull that discussion into here because we're going to have to care about this for 0.12 maintenance at least. We should ensure that we have synchronized goals and ideas about what LTS means so that we don't end up in conflict about what we're happy to pull in for npm for LTS releases.

@zkat perhaps you could tune us in to ongoing discussions about npm LTS or maybe someone over there could join our meeting next week to sync? Monday 1pm PT.

**Comment by jasnell** [comment]
@zkat ... would you be able to join us for the next LTS WG meeting to discuss npm LTS?

**Comment by zkat** [comment]
Hey! Sorry for the delay. I had trouble pinning down the info I needed to be able to give you a good response about this.

But now I have it! So!

I can do next Monday at 13:00 PT if that's alright, assuming that's still the time for it? :)

/cc @othiym23

**Comment by othiym23** [comment]
I will do my best to get @zkat up to speed with my (wooly, vague) thoughts about how npm can best support the LTS process before the meeting.

**Comment by jasnell** [comment]
@zkat @othiym23 :+1: thank you both very much

**Comment by jasnell** [comment]
Closing this in favor of https://github.com/nodejs/LTS/issues/37
