### ISSUE TITLE
npm update for 0.12

### ISSUE THREAD

**Issue by rvagg** [nodejs/LTS#143]
As per https://github.com/nodejs/node/pull/8928, thanks to @ChALkeR for the ping. The LICENSE is finally updated in npm@2, it might be appropriate for us to ship this in both 0.10 and 0.12 since we're still shipping the old, problematic license. Thoughts @nodejs/lts?

**Comment by jasnell** [comment]
We certainly could. Is that by itself enough to justify a new release of v0.10 tho?

**Comment by mhdawson** [comment]
I'm not sure its worth it for 0.10.X.  Its been the way it is for a long time and 0.10.x should only be in use for a few more weeks.

**Comment by rvagg** [comment]
> should only be in use for a few more weeks

![screenshot 2016-10-13 11 05 10](https://cloud.githubusercontent.com/assets/495647/19407431/d8582000-92ed-11e6-9632-ed7fe413cb9c.png)

That's 0.10 in the **blue** there not doing a very good job at dying, unlike 0.12.

It's going to be used a lot longer than that, particularly given that it's included in some Linux distros that will live for a long time. I'd argue that getting a release out with a correct license is the responsible thing to do with a release line that folks are already having a hard time considering giving up on.

**Comment by rvagg** [comment]
![screenshot 2016-10-15 15 46 20](https://cloud.githubusercontent.com/assets/495647/19407463/8b5be2cc-92ee-11e6-84f6-813d86171efa.png)

Labelled version cause I realise there's more interesting stuff in here for folks.

**Comment by TheAlphaNerd** [comment]
I'd be up for putting together a 0.10 and 0.12 release including the npm
update and the cares patch

**Comment by rvagg** [comment]
@TheAlphaNerd I think we should still stick to our process of not bundling non-trivial and non-build things with security releases so this would actually mean two releases, one for c-ares and one for npm

**Comment by TheAlphaNerd** [comment]
It was decided on today's call that @Fishrock123 would backport to v0.12 and that we would have a no-op for 0.10

this issue should be closed when the PR is opened, I am going to edit the title to reflect the current state of things

**Comment by ErisDS** [comment]
Sorry I couldn't be there this time. Can you explain what no-op for 0.10 means?

**Comment by Fishrock123** [comment]
0.10 is EOL so we are not going to another release in any official capacity.

**Comment by TheAlphaNerd** [comment]
@ErisDS yeah, sorry for the poor choice of wording there. We will not be doing another 0.10 release is what I meant to say

**Comment by Fishrock123** [comment]
Closing, moving to the PR: https://github.com/nodejs/node/pull/9619
