### ISSUE TITLE
upgrade issue from node v 4.2.6 to LTS

### ISSUE THREAD

**Issue by pandeysoni** [nodejs/LTS#146]
I run these command:

sudo npm cache clean --force
sudo npm install -g n
sudo n 6.0.0

After that i see on cli:
 install : node-v6.0.0
       mkdir : /usr/local/n/versions/node/6.0.0
       fetch : https://nodejs.org/dist/v6.0.0/node-v6.0.0-linux-x64.tar.gz
######################################################################## 100.0%
   installed : v6.0.0

but when i run node -v, still i found previous version of node.

**Comment by cjihrig** [comment]
You could have some `PATH` issues. This doesn't appear to be a problem with Node core though. Could you try asking this question on the `n` issue tracker or https://github.com/nodejs/help.
