### ISSUE TITLE
Problem using Crypto on Node 4.6.0

### ISSUE THREAD

**Issue by cperezvinsite** [nodejs/LTS#154]
I have 2 Raspberries Pi and one Mac computer, in all of them I have installed nodejs width NVM using 4.6.0

I need to create a hash using crypto lib, ie. <code>var passSalt = crypto.pbkdf2Sync(“a”,”1”, 10000, 512, ‘sha512').toString('base64')</code>

The return in the mac and the raspberry width 2015-09-24-raspbian-jessie is the same, BUT when i run this line <code>var passSalt = crypto.pbkdf2Sync(“a”,”1”, 10000, 512, ‘sha512').toString('base64')</code> in the Raspberry width 
RASPBIAN JESSIE LITE 09-2016 the output is complete diferent and this breaks my authentication system

I tried changing the iteration number from 10000 to 0 or 1 but the output still different

**Comment by bnoordhuis** [comment]
It would help if you explain exactly how it's different.  Can you post the output of `node -p process.versions` and `uname -a` for all three systems?  Thanks.

**Comment by bnoordhuis** [comment]
Aside, this is not really the right issue tracker to report runtime bugs, that's https://github.com/nodejs/node/issues.

**Comment by cperezvinsite** [comment]
https://github.com/nodejs/node/issues/9585
