### ISSUE TITLE
LTS WG Meeting - 2016-11-14 8:00 PM UTC

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/LTS#155]
## Invited

@nodejs/lts 

## When

8PM Monday November 14 UTC, or in your local timezone:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20161114T16&p1=179&ah=1

## Where

Hangouts on Air:
- Observers: http://youtu.be/NchA8x-uAFo
- Participants: https://hangouts.google.com/call/ltwuwrzhtfdvzgzz5orn66xjkye

### nodejs/LTS
- Status and plan for v6 LTS [#153](https://github.com/nodejs/LTS/issues/153)
- npm update for 0.10 and 0.12 [#143](https://github.com/nodejs/LTS/issues/143)

### Other discussion
- Release date for next v4 and v6 releases

## Minutes

https://docs.google.com/document/d/1arT9wEirqUnd-Itj9x71His3J8eVi2b2c2KRlTZvuvg/

**Comment by TheAlphaNerd** [comment]
It is worth mentioning that the agenda is fairly sparse today. I believe that most of these issues can be managed in github threads if we want to call of the meeting.

**Comment by mhdawson** [comment]
I'll be there

**Comment by TheAlphaNerd** [comment]
Great meeting ya'll
