### ISSUE TITLE
Audit a Node.js Backporting Session

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#156]
Are you interested in learning more about how we backport code. Please fill out this doodle with available times and we are going to pick a morning an afternoon this week to stream for 30 minutes to an hour of the process with open questions

http://doodle.com/poll/2ni9rv3yerv9x6bm

**Comment by destroyerofbuilds** [comment]
I'm following this repository a little late, but I'd be interested in learning more about the backport process should you hold another streaming session in the future.

**Comment by gibfahn** [comment]
>I'm following this repository a little late, but I'd be interested in learning more about the backport process should you hold another streaming session in the future.

Just discovered this, @destroyerofbuilds if you're still interested in the backporting process we've got a team now, and going forwards it should be easier to get involved.

**Comment by MylesBorins** [comment]
we should plan another live backporting thing!
