### ISSUE TITLE
Release plan for v4 / v6 until April 2017

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#159]
We are planning monthly releases on the first Tuesday of every month for v4 and v6, and a single v0.12 release in the first week of December. Currently our only planned _Semver-Minor_ release if v4.7.0 on December 6th, but it is possible that one of the patch releases on v4 or v6 could be a minor release if deemed necessary by the LTS Working Group. These dates are also subject to change based on the need for security releases.

**February 21st**

Release of _v4.8.0_ and _v6.10.0_

**March 21st**

Release of _v4.8.1_ and _v6.10.1_

**Comment by TheAlphaNerd** [comment]
Please let me know if you have problems with the dates above. I would also be interested if individuals think the information above could be presented in a clearer fashion. I'm also interested if individuals think that the above information should be present in the repo's readme.

**Comment by AdriVanHoudt** [comment]
Can it be visualised on the current (most used?) LTS visualisation from Nodesource? ![](http://i1-news.softpedia-static.com/images/news2/node-js-version-6-released-with-long-term-support-503452-3.png)

**Comment by rvagg** [comment]
@AdriVanHoudt that might give the impression that these dates are more concrete than they are, there's a bunch of factors that could easily change these plans, most notably security releases which could change version numbers and bump dates if they are too close.

**Comment by AdriVanHoudt** [comment]
@rvagg good point, it was just my initial thought on `could be presented in a clearer fashion` but you are right if they are not final it probably just a case of where to put the info

**Comment by destroyerofbuilds** [comment]
I agree with @rvagg that the information should not be coupled with the LTS release schedule.

I do think the schedule should be posted to the `README`. A comment, in the form of a quote, above the schedule would be fine for the purpose of educating the community that the release schedule should be considered "best effort", but is subject to change.

Posting the schedule to the `README`, in my opinion, makes the schedule, and the best intentions of the LTS group, feel more _legit_ than an issue.

**Comment by TheAlphaNerd** [comment]
these dates are subject to change enough due to security updates that I do
not feel comfortable putting it in the Readme

**Comment by hbetts** [comment]
In that case, I find the formatting of the dates in the original issue comment to be readable, and this issue to be sufficient; with the caveat that it would be helpful if the issue's original comment is kept up-to-date (so that I do not need to parse the entire thread to grasp the current state of your release plans).

**Comment by TheAlphaNerd** [comment]
rad. currently no changes to the release plan.  we will update the first
comment if anything changes

**Comment by richardlau** [comment]
@MylesBorins Maybe update the first comment to take into account the point releases made earlier today?

**Comment by MylesBorins** [comment]
@richardlau good call!

**Comment by mhdawson** [comment]
@MylesBorins should we be adding the schedule for the next 2 releases as well ? Possibly:

April 24th

Release of v4.9 (as Quarterly semver minor starting off Maintenance phase) and v6.11

May 23rd

Release v6.11.1

**Comment by MylesBorins** [comment]
@mhdawson based on the schedule v4 is moving to maintenance mode as of April 1st. We just did a semver minor last month, so I think it is a bit soon to do the minor for v6.

I'll put together a new issue for our Q2 release schedule next week
