### ISSUE TITLE
v8 LTS codename

### ISSUE THREAD

**Issue by rvagg** [nodejs/LTS#163]
As I find myself continuing to trip over the name "v8" for obvious reasons, I'm wondering if one possible solution might be to choose a codename early so that we can start referring to the LTS version of v8 by its codename. A drawback of course is that it may become associated with the Current period of v8 and confuse part of the purpose of the codenames (to highlight LTS). Nonetheless it's worth considering at least and I'd like to hear more thoughts on the topic.

Regardless, here's the complete list from which we need to come up with a short list of 3 or 4 to present to the full collaborator group for voting. There's probably some obvious ones to cull but I'll present them first without comment.

## Cadmium - Cd

Cadmium is a lustrous, silver-white, ductile, very malleable metal. Its surface has a bluish tinge and the metal is soft enough to be cut with a knife, but it tarnishes in air. It is soluble in acids but not in alkalis. It is similar in many respects to zinc but it forms more complex compounds.

## Calcium - Ca

The chemical element Calcium (Ca), atomic number 20, is the fifth element and the third most abundant metal in the earth’s crust. The metal is trimorphic, harder than sodium, but softer than aluminium. As well as beryllium and aluminium, and unlike the alkaline metals, it doesn’t cause skin-burns. It is less chemically reactive than alkaline metals and than the other alkaline-earth metals. 

## Californium - Cf

Californium is a radioactive metal which is a member of the actinide group of the periodic table. A sample of the metal itself has not been produced yet because its compounds resist reduction. It is expected to be readily attacked by air, steam and acids and not by alkalis.

## Carbon - C

Carbon is unique in its chemical properties because it forms a number of components superior than the total addition of all the other elements in combination with each other.

The biggest group of all these components is the one formed by carbon and hydrogen. We know a minimum of about 1 million organic components and this number increases rapidly every year. Although the classification is not strict, carbon forms another series of compounds considered as inorganic, in a much lower number than that of the organic compounds.

## Cerium - Ce

Cerium is a malleable, soft, ductile, iron-grey metal, slightly harder than lead. It is very reactive: it tarnishes readily in the air, it oxidizes slowly in cold water and rapidly in hot water. It dissolves in acids. It can burn when heated or scratched with a knife. 

## Cesium - Cs

The metal is characterised by a spectrum containing two bright lines in the blue (accounting for its name). It is silvery gold, soft, and ductile. It is the most electropositive and most alkaline element. Cesium, gallium, and mercury are the only three metals that are liquid at or around room temperature. Cesium reacts explosively with cold water, and reacts with ice at temperatures above -116°C. Cesium hydroxide is a strong base and attacks glass. Cesium reacts with the halogens to form a fluoride, chloride, bromide, and iodide. Cesium metal oxidized rapidly when exposed to the air and can form the dangerous superoxide on its surface. 

## Chlorine - Cl

Discovered in 1774 by Carl Wilhelm Scheele, who mistakenly thought it contained oxygen. Chlorine was given its name in 1810 by Humphry Davy, who insisted that it was in fact an element.

The pure chemical element has the physical form of a diatomic green gas. The name chlorine is derived from chloros, meaning green, referring to the color of the gas. Chlorine gas is two and one half times as heavy as air, has an intensely disagreeable suffocating odor, and is exceedingly poisonous. In its liquid and solid form it is a powerful oxidizing, bleaching, and disinfecting agent.

This element is a part of the halogen series forming salts. It is extracted from chlorides through oxidation and electrolysis. Chlorine gas is greenish-yellow and combines readily with nearly all other elements. 

## Chromium - Cr

Chromium is a lustrous, brittle, hard metal. Its colour is silver-gray and it can be highly polished. It does not tarnish in air, when heated it burns and forms the green chromic oxide. Chromium is unstable in oxygen, it immediately produces a thin oxide layer that is impermeable to oxygen and protects the metal below.

## Cobalt - Co

Cobalt is a hard ferromagnetic, silver-white, hard, lustrous, brittle element. It is a member of group VIII of the periodic table. Like iron, it can be magnetized. It is similar to iron and nickel in its physical properties. The element is active chemically, forming many compounds. Cobalt is stable in air and unaffected by water, but is slowly attacked by dilute acids.

## Copper - Cu

Copper is a reddish metal with a face-centered cubic crystalline structure. It reflects red and orange light and absorbs other frequencies in the visible spectrum, due to its band structure, so it as a nice reddish color. It is malleable, ductile, and an extremely good conductor of both heat and electricity. It is softer than zinc and can be polished to a bright finish. It is found in group Ib of the periodic table, together with silver and gold. Copper has low chemical reactivity. In moist air it slowly forms a greenish surface film called patina; this coating protects the metal from further attack.

## Curium - Cm

Named after Pierre and Marie Curie. Curium is a hard, brittle, silvery metal that tarnishes slowly in dry air at room temperature. Curium does not occur naturally; it is typically produced artificially in nuclear reactors through successive neutron captures by plutonium and americium isotopes.

Curium is very radioactive, more electropositive than Aluminum, chenically reactive. A few compounds of curium are known, as the fluorides.

**Comment by italoacasas** [comment]
I feel like `v8 Chromium` is going to be confusing.

**Comment by TheAlphaNerd** [comment]
carbon seems like a nice one.

as confusing as it may be, chromium definitely has me laughing quite a bit

**Comment by ofrobots** [comment]
Has there been any discussion of skipping the v8.x and v9.x and going straight to v10.x?

**Comment by TheAlphaNerd** [comment]
@ofrobots it has been bright up, but I don't think in any capacity that was
official. do you think this is cometh in the ctc should vote on?

**Comment by cjihrig** [comment]
I like Carbon as well. All Node developers are carbon based lifeforms.

**Comment by ofrobots** [comment]
I personally have fumbled with V8 vs. `v8.x` a lot – and it is a lot harder to distinguish when spoken. Note that a lot of people – not just Node.js core but the whole ecosystem – will have to live with this confusion with a very long time (until April 2020 when 'C* LTS' goes out of support).

I do think we should discuss this and be deliberate about the pros and cons of skipping version numbers to reduce confusion.

**Comment by sam-github** [comment]
I dislike (because I cannot remember them) code names, and doubt people will use them. Aren't there already names for node releases that we all ignore? Lets skip version 8 and go to 9. majors are cheap, they are just numbers.

**Comment by bnoordhuis** [comment]
I'm okay with skipping a version number.  That would also dispel people of the notion that even is stable, odd is unstable.
 
> I like Carbon as well. All Node developers are carbon based lifeforms.

[Carbon chauvinism!](https://en.wikipedia.org/wiki/Carbon_chauvinism)

**Comment by kgryte** [comment]
I am __not__ okay with skipping a version number. If Node skipped version `8` and went to version `9`, this would break the pattern that even versions are LTS and odd are non-LTS. Second, if Node skips, this will have to be explained (just in a different way to `v8` vs `v8`). That `v8` happens to overlap with the abbreviation for `version 8` is accidental and should not be a determining factor in breaking convention; i.e., that versions follow in successive order and that even are LTS and odd non-LTS.

Treating versions as just numbers plays fast and loose with people's expectations.

**Comment by TheAlphaNerd** [comment]
I'm under the impression that if we were to skip we would go directly to 10

**Comment by italoacasas** [comment]
In the long shot, I feel is going to be easier to explain... `It's not that v8` sometimes, that explaining `node v8 do not exist because`.

**Comment by Fishrock123** [comment]
`Chromium` overlaps with, well... google chrome. So we can cross that out I think.

`Carbon`, `Cobalt`, and `Copper` are all short, relatively common, and easier to pronounce than many of the others.

**Comment by jasnell** [comment]
At the Collaborator Summit it was discussed and decided that the best path forward would be to drop the leading 'v' in the version reference when referring to Node.js releases in order to avoid the potential 'v8.0.0' vs. 'V8' confusion.

It was also discussed and decided that choosing the codename for the Node.js 8.x LTS release in advance would be desirable as a way of providing future reference. However, it is important to note that any 8.x release happening *before* the official transition of the 8.x stream into LTS would **not** be referred to by the codename. The codename only applies after the LTS transition has occurred.

As for the specific codenames, I am +1 on `Carbon`, `Cobalt`, and `Copper` as the choices for 8.x. If we are going to select the names in advance, we should open a voting thread in March in advance of the release in late April.

**Comment by richardlau** [comment]
Would dropping the 'v' include `process.version` (which currently has the 'v' -- `process.versions.node` does not) or is this purely communications?

**Comment by jasnell** [comment]
At this point purely communications. There were no plans discussed to change the `process.version` or the output of `node -v`. Doing so would needlessly break running code so likely should be avoided

**Comment by mhdawson** [comment]
+1 on Carbon and Copper from me.

**Comment by sam-github** [comment]
+1 on dropping the "v", an elegant solution.

-1 on code names, for the record, though I understand I'm likely in the minority here. I'll be commenting on every use of the code name in our communications that doesn't use an actual version number, though.

Why node would stop using semver to communicate its version with users so recently after moving to proper semver is beyond me. And why arbitrary chemical names are easier to remember than increasing numbers is beyond me, too. Generally, having two names for the *exact same thing* is considered a problem, not a solution.

Sure, Apple does it, but their user's don't know or care about semver, and Ubuntu does it (so every time I see the awful names I have to go to wikipedia to see what version they meant, which is quite annoying, especially when they have such a beautiful version number, that indicates the release time, does anybody remember when the "goofy gander" was released? Me either.), but that doesn't mean we should follow in their footstep.

If we like letters as versions so much, why not have semver be `[a-z]+.decimal.decimal`? Other than that its silly.

OK, said my piece... let the double naming commence.

**Comment by jasnell** [comment]
Node.js would not stop using semver at all to communicate it's version. We would continue following the pattern we have been for Node.js 4 and 6 -- that is, the codename does not, in any way, replace the use of semver. 

It is important to note that semver does not have any mechanism for dealing with Long Term Support and the codename applies **only** to Long Term Support. Specifically, the codename only applies to Node.js releases that are covered by the LTS process.

**Comment by alexprice91** [comment]
Pull a windows and skip to v10

**Comment by kyrylkov** [comment]
+1 for `Carbon` and dropping `v`

**Comment by jasnell** [comment]
@nodejs/lts ... it's time that we finalized this decision so that we know what the name is going to be. I will be cutting the 8.x and 8.x-staging branches within the next two weeks in preparation for the April release.

**Comment by italoacasas** [comment]
I see Carbon 7 times.

**Comment by NawarA** [comment]
Carbon, now 8 times

**Comment by andmeics** [comment]
Carbon and Copper from me.

**Comment by jasnell** [comment]
@nodejs/lts @nodejs/ctc ... are we ready to call it? Looks like `Carbon` is the clear leader here.

**Comment by rvagg** [comment]
+1 let's call it, @nodejs/collaborators please weigh in on naming before next week, @nodejs/ctc let's make a decision at next week's meeting.

**Comment by estliberitas** [comment]
+1 for Carbon!

**Comment by targos** [comment]
+1 for `Carbon` or `Cobalt`

**Comment by mcollina** [comment]
+1 for Carbon

**Comment by abouthiroppy** [comment]
+1 for `Carbon` ;)

**Comment by princejwesley** [comment]
+1 for carbon

**Comment by evanlucas** [comment]
+1 for carbon

**Comment by jbergstroem** [comment]
`Carbon` +1

**Comment by julianduque** [comment]
Carbon!

**Comment by gibfahn** [comment]
Carbon

**Comment by alexprice91** [comment]
Copper + 10

**Comment by MylesBorins** [comment]
in a conversation with @bmeck we have discovered that there is no element that starts with `j`, `q`, or `w`

We have 5 years to discover a new element or our naming conventions are going to break

**Comment by Fishrock123** [comment]
@rvagg wait are we fully deciding a name or narrowing down to have a vote between a couple?

**Comment by bengl** [comment]
> We have 5 years to discover a new element or our naming conventions are going to break

Alternatively, skip those letters, and then we get to loop around and use Curium sooner.

**Comment by migg24** [comment]
@MylesBorins You could use the German words for some elements as an international platform:

J: Jod (I)
Q: Quecksilber (Hg)
W: Wasserstoff(H), Wolfram (W)

Problem solved ✅

**Comment by NawarA** [comment]
If we went by the periodic table of elements, we'd be good on how long this convention would last us. 

We'd be on Lithium or Oxygen right now

**Comment by Trott** [comment]
Would it be OK to take this off the CTC agenda and let @nodejs/lts decide the code name?

If they want to do it by tallying votes like they did apparently did for Boron (see https://github.com/nodejs/node/issues/8026), then great. And if they want to just decide based on this thread because it's kind of lopsided for Carbon, then also great. 

The LTS README says there will be a collaborator vote. Is this issue sufficient to constitute that vote? That's something I"m happy to let @nodejs/lts decide.

I don't think code names involved CTC before and I'd rather not set that as a precedent if we don't have to.

**Comment by rvagg** [comment]
@Trott yeah, good call, I've removed the label. In the past we've left this to LTS to decide rather than the CTC so it was a mistake to palm it off anyway! Looks like we have a heavy lean toward Carbon but the next LTS meeting can ratify that.

**Comment by jasnell** [comment]
I believe we can likely ratify it in advance of the meeting really. Carbon is hands down the clear leader. @nodejs/lts ... any objections to going with `Carbon` as the codename for 8.x?

**Comment by MylesBorins** [comment]
SGTM

**Comment by gibfahn** [comment]
SGTM

**Comment by mhdawson** [comment]
SGTM

**Comment by rvagg** [comment]
LGTM! Make it so!

**Comment by jasnell** [comment]
The code name has been selected. It is `carbon`. Closing this.
