### ISSUE TITLE
Document that changes must be in Current before backporting

### ISSUE THREAD

**Issue by destroyerofbuilds** [nodejs/LTS#164]
As noted by @TheAlphaNerd [here](https://github.com/nodejs/node/pull/9139#issuecomment-264543910), changes must be in a _Current_ release for 2 weeks before they may be backported.

I could not find that documented on the LTS [README](https://github.com/nodejs/LTS).

**Comment by TheAlphaNerd** [comment]
do you want to send a pr to the Readme?

**Comment by hbetts** [comment]
@TheAlphaNerd please feel free to assign the issue to me.

I've already filed #165

**Comment by mhdawson** [comment]
@hbetts looks like your PR landed, so going to close this, please re-open if you dis-agree.
