### ISSUE TITLE
Node.js - Quality with Speed

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#172]
I worked with Myles to put together a doc that tries to pull together a number of things that we as a community have been doing over the last few years and explain how they fit into the bigger picture of delivering Node.js:

https://gist.github.com/mhdawson/69d05e4cccab2b9a8ef50f8a0c13e71c#file-qualitywithspeed-md

The goal is to make the case that we have good processes in place and that we achieve a good rate of change while also achieving a good level of quality.

We'd like input on how to best land this.  We've talked about putting it out as a blog (Node.js or IBM as appropriate) or even landing as a doc in the LTS or one of the other repos.

Posting this to get input on what people think makes the most sense.

**Comment by mhdawson** [comment]
@nodejs/lts for initial comment.

**Comment by Fishrock123** [comment]
Maybe we should LTS agenda it for visibility, but this should definitely go on the website IMO.

**Comment by mhdawson** [comment]
PR opened in node.js org I think we can close this one.
