### ISSUE TITLE
How to install Node.js ?

### ISSUE THREAD

**Issue by davduf** [nodejs/LTS#176]
Hello,

I d/l https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.xz
But i don't know what I have to do after?

I am on Ubuntu 16.04

Thank you very much !

**Comment by gibfahn** [comment]
See this: https://github.com/nodejs/help/issues/418

If you still have issues afterwards please comment on that thread, nodejs/help is the place for it.

**Comment by davduf** [comment]
great ! Thx!
