### ISSUE TITLE
LTS WG Meeting - 2017-01-09 9:00 PM UTC

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#179]
## Present

@nodejs/lts

## When

9PM Monday January 9th UTC, or in your local timezone:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20170109T16&p1=179&ah=1

## Where

Hangouts on Air:
- Observers: https://www.youtube.com/watch?v=2bfd9NjO_SE
- Participants: https://hangouts.google.com/call/fmno4whhrbazfgu2xtry7bgwl4e

### nodejs/LTS

- Potential SemverMinor Backports [#177](https://github.com/nodejs/LTS/issues/177)
- Should we move to a 3 week cadence  [#173](https://github.com/nodejs/LTS/issues/173)
- Node.js: Quality with Speed [#172](https://github.com/nodejs/LTS/issues/172)

### other

- discuss release dates 

## Minutes

https://docs.google.com/document/d/1YK6hYnaVAgGIYC50I8utpx7mD_L-E_127CuuymE3YvU/edit?usp=sharing

**Comment by williamkapke** [comment]
Node.js Foundation calendar: https://calendar.google.com/calendar/embed?src=kap.co_i17i575te0aes6kaanfjr2e4hs%40group.calendar.google.com

I added this time slot @ every 3 weeks.

**Comment by williamkapke** [comment]
@MylesBorins LMK if you object to me copying this video to the official Node.js YouTube channel.

**Comment by MylesBorins** [comment]
go for it!

**Comment by williamkapke** [comment]
Video Here: https://youtu.be/-XrP2oDMFBo

**Comment by MylesBorins** [comment]
Thanks everyone!
