### ISSUE TITLE
Relationship with Nan

### ISSUE THREAD

**Issue by mcollina** [nodejs/LTS#18]
I see no mention of Nan in this repo, while it is a critical component of my daily maintanance of modules.

I think Nan should support all current LTS releases. It is probably implied, but probably it is worth specifying it for newcomers.

**Comment by rvagg** [comment]
@mcollina implicit, but I agree that it'd be worth stating, we'd have to state it as a goal for now and get agreement from @nodejs/addon-api because that's where that work will have to be done.

**Comment by jasnell** [comment]
Adding some language to the readme to cover this.
