### ISSUE TITLE
backporting WG

### ISSUE THREAD

**Issue by sam-github** [nodejs/LTS#184]
Hey All

So I'm doing another batch backport and I think that we really need to take a moment to re-evaluate our process and distribute the workload.

I'd like to suggest that we make a backporting team, potentially a sub committee of the LTS group. This team should hold a couple meetings to properly figure out how to distribute the workload. Part of this will be re-imagining the current labelling process and meta data process.

with that being said I think it makes sense for us to block movement on this doc for now. Then use this doc as a starting point for the backporting team.

The number 1 thing I would like to see is a doc being drafted by / agreed upon by the people who are going to volunteer to do the work.

- @MylesBorins from https://github.com/nodejs/node/pull/11099#issuecomment-284589389

**Comment by sam-github** [comment]
This got lots of thumbs up, how do we make it happen? Organize a call? Add a call to tail-end of the next LTS WG meeting?

**Comment by MylesBorins** [comment]
We should tag this on to a future LTS WG meeting. I'm OOO next Monday, but if we are all willing to push it until Tuesday I think I can make it work.

**Comment by sam-github** [comment]
I'm on vacation next week, but could do later evening (but not Tuesday evening) or early morning PST. Maybe we need a doodle? Could we do this Friday? Not that my presence is required ;-). I trust @gibfahn to speak for me.

**Comment by gibfahn** [comment]
I think this is completed (team exists and we're sharing the workload).
