### ISSUE TITLE
LTS Meeting March 13 - 5 EST

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#185]
## Present

@nodejs/lts

## When

9PM Monday March 13 UTC, or in your local timezone:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20170313T17&p1=179&ah=1

## Where

Hangouts on Air:
- Observers: https://www.youtube.com/watch?v=w45MlYvMSQM
- Participants: https://hangouts.google.com/hangouts/_/ytl/2trzQTKp0iq8gJB3R9NQKETNpBIx8XZbOyLDTb8YI10=?eid=100598160817214911030
- Events page: https://www.youtube.com/my_live_events

### nodejs/LTS

* Potential Semver Minor Backports lts-agenda [#177] (https://github.com/nodejs/LTS/issues/177)
* Should we consider swapping the timeframe for Active LTS and Maitanance lts-agenda [#130 ] (https://github.com/nodejs/LTS/issues/130)
* Managing floating V8 patches lts-agenda [#111]https://github.com/nodejs/LTS/issues/111)

### other
* Backporting WG [#184](https://github.com/nodejs/LTS/issues/184)

## Minutes

Should we consider swapping the timeframe for Active LTS and Maitanance lts-agenda [#130 ] (https://github.com/nodejs/LTS/issues/130)

https://docs.google.com/document/d/1qaloPiXAZd5Pf3H0CtzW7m5kk-ahOKZg622KXAr8ehE/edit

**Comment by MylesBorins** [comment]
thanks for taking the lead @mhdawson I've been pretty buried and really appreciate the help

**Comment by gibfahn** [comment]
I'd like to join this meeting if possible (not sure what the rules are for joining these meetings).

**Comment by mhdawson** [comment]
@MylesBorins I saw a comment on another issue about you being out today ?  Are you going to be able to make it.  I've set the time/date to match what is in the community google calendar.

**Comment by mhdawson** [comment]
@gibfahn, I'd say just join, I don't think there will be any objections.

**Comment by mhdawson** [comment]
Added hangouts link: https://hangouts.google.com/hangouts/_/ytl/2trzQTKp0iq8gJB3R9NQKETNpBIx8XZbOyLDTb8YI10=?eid=100598160817214911030

**Comment by mhdawson** [comment]
I'll plan to post the PR for the minutes in the next day or so.

**Comment by mhdawson** [comment]
PR for minutes: https://github.com/nodejs/LTS/pull/187

**Comment by binoculars** [comment]
LTS Codename?

Logical choices seem to be a _C_ from the periodic table, which comes down to:
- Cadmium
- Calcium
- Californium
- Carbon
- Cerium
- Cesium
- Chlorine
- Chromium
- Cobalt
- Copper
- Curium

Carbon seems like the best fit, with a low atomic number, and ends in -on like the 2 other codenames. Chromium, would be too confusing.

**Comment by mhdawson** [comment]
@binoculars codename is being discussed here: https://github.com/nodejs/LTS/issues/163

**Comment by gibfahn** [comment]
Minutes landed, closing...
