### ISSUE TITLE
Node-v8 LTS support end on 2019-12-31 to meet EOSL of openssl-1.0.2

### ISSUE THREAD

**Issue by shigeki** [nodejs/LTS#186]
According to the support policy of openssl-1.0.2, Node-v8 LTS support end is 2019-12-31 that is about 3 months earlier than our plan  if we continue to use openssl-1.0.2.
See https://github.com/nodejs/node/pull/11828.

**Comment by mhdawson** [comment]
This seems like a reasonable deviation, and its good if we document from the outset of Node version 8 so there should be no surprises later on.

**Comment by sam-github** [comment]
@nodejs/lts can one of you add the `lts-agenda` label to this?

**Comment by jasnell** [comment]
This is unfortunate but likely necessary. Fortunately it will not impact the scheduling of the active LTS period. I will get this updated in the schedule

**Comment by gibfahn** [comment]
It sounds to me like we're going to default to this assuming there are no objections (and #133 already updated [the schedule](https://github.com/nodejs/LTS#lts-schedule1) to reflect this).

**Comment by gibfahn** [comment]
There were no objections in the meeting, so this is decided.

**Comment by mohammadjnoor** [comment]
@sam-github

**Comment by mohammadjnoor** [comment]
@sam-github
