### ISSUE TITLE
request to join LTS wg

### ISSUE THREAD

**Issue by sam-github** [nodejs/LTS#189]
I have time to work on backports, and would like to participate in the backporting process, both doing the work and working on the process/tooling for backporting and tracking backport state.

I'm not sure what "joining" means officially, but I'd like to be invited to participate in the WG meetings, and it would likely be useful for me to have write access to http://github.com/nodejs/LTS

**Comment by gibfahn** [comment]
Me too, not least because the new Backporting team/WG/whatever is I think going to be a subset of the LTS WG.

**Comment by MylesBorins** [comment]
+1

**Comment by sam-github** [comment]
@gibfahn should also join, if he is not already because he will also be continuing to work on backports.

**Comment by sam-github** [comment]
@MylesBorins or @mhdawson, can you add @gibfahn and I to the github nodejs/LTS org? It would allow us to label issues.

**Comment by MylesBorins** [comment]
Done

**Comment by refack** [comment]
me 4...
