### ISSUE TITLE
Simplify wording

### ISSUE THREAD

**Issue by mcollina** [nodejs/LTS#19]
I think the document is fairly low-level, as it assume one knows very well the node/iojs dev cycle, what next is, and all the problema correlated to V8 versions.

Most developers do no have this knowledge, so we should add a TLDR; thing that is easily understandable.

**Comment by jasnell** [comment]
@mcollina ... agreed. At this point, however, we're largely still working out the higher level details. Once we're sure the plan is stable, and once it's clear how the `next` and `master` release policy discussions will conclude, I'll work on summarizing this a bit better.

**Comment by mcollina** [comment]
Feedback from the community was asked, but in order to provide feedbacks
they need to understand.

At the bare minimum, let's write the problem LTS aims to solve. Why V8
versions are problematic, what is next and master.
Il giorno mar 7 lug 2015 alle 18:56 James M Snell <notifications@github.com>
ha scritto:

**Comment by TheAlphaNerd** [comment]
@mcollina I am going to close this for now. Please re open if you would like to continue the discussion
