### ISSUE TITLE
What day is Node.js 8 due?

### ISSUE THREAD

**Issue by franciscop** [nodejs/LTS#190]
I see from the repo that it is due in April 2017 (next month), but will it be released any specific day? Or is it not determined yet?

Edit: I am asking because I'm preparing to [release a library](https://serverjs.io/) and do a workshop with the version 8 as it's the first LTS version that supports `async`/`await`, and I'd prefer to do it with these new JS concepts instead of having to explain the old ones and the migration path.

**Comment by MylesBorins** [comment]
@franciscop version 8 will be cut in april, but it will not be moved to LTS for another 6 months.

**Comment by gibfahn** [comment]
@franciscop the table will be updated in https://github.com/nodejs/LTS/pull/133, but if you want the blow-by-blow account, you can follow https://github.com/nodejs/node/issues/10117.

**Comment by franciscop** [comment]
@gibfahn awesome, I see that they'll wait for V8 5.8 becomes stable in mid-april and then try to launch it before April ends. Guestimate there is April 25th.

**Comment by ziedHamdi** [comment]
So? we're waiting for the async await feature for 2 months now. I don't see any teasing about the v8 being launched. Are there any news please?

**Comment by cjihrig** [comment]
You can follow the progress of Node 8 [here](https://github.com/nodejs/node/pull/12220).

**Comment by addaleax** [comment]
@ziedHamdi We pushed the release date for Node 8 because of [this](https://github.com/nodejs/CTC/issues/99). if you follow @cjihrig’s link, you’ll see that the new target release date is May 30th. Also: You can already use async/await in Node 7, no need to wait for anything.

**Comment by tunnckoCore** [comment]
@ziedHamdi >=7.6 has native async/await support :)

**Comment by ziedHamdi** [comment]
Hi @tunnckoCore, sure! thanks for the info. Unfortunately we're going to production this month, so it's no way for us to deploy node 7.x

 thanks anyway :)

**Comment by ziedHamdi** [comment]
Hi @cjihrig @addaleax , thanks for the details replies. I didn't find that links in google search. This discussion is the best referenced one when searching "node js 8 release date"

**Comment by wbhob** [comment]
The release date has been moved to May 30, 2017.

**Comment by tuananh** [comment]
Just saw rc1 build up at https://nodejs.org/download/rc/v8.0.0-rc.1/

**Comment by oooooo99999** [comment]
https://www.federalregister.gov/presidential-documents/executive-orders
