### ISSUE TITLE
Backporting Team Meeting, April 12th 2017

### ISSUE THREAD

**Issue by gibfahn** [nodejs/LTS#191]
## Meeting:

 - Meeting time:  Wed 12 April 18:00-19:00 BST, 13:00-14:00 EST, [Time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Backporting+Meeting&iso=20170412T18&p1=136&ah=1)
 - Location: https://hangouts.google.com/hangouts/_/mdk6v3wgf5cxlptxct7auynalye
 - Notes: https://docs.google.com/document/d/1LYZSogVnopZDbf6F-qROeDOAiNHEhwAkWrXcWAQNe40/edit

## Background

It was agreed at the [last LTS meeting](https://github.com/nodejs/LTS/issues/185) that we'd set up a Backporting Team to work on improving the backporting process (and also doing the backporting).

Refs: https://github.com/nodejs/LTS/issues/184

The initial list was going to be: @jasnell @MylesBorins @sam-github @gibfahn, also cc/ @mhdawson 

 - ~Doodle poll for this week: http://doodle.com/poll/543s5ivcqgvy83gf~
 - ~Meeting time:  19:00-20:00 BST, 14:00-15:00 EST, [Time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Backporting+Meeting&iso=20170331T19&p1=136&ah=1)~
- ~Doodle poll for next Monday/Tuesday: http://doodle.com/poll/t5gu4pwpcxd7cpdg~
- Doodle poll for next Monday-Thursday http://doodle.com/poll/2i7i83h9vii9k7pu

 - Youtube for those who want to watch: https://www.youtube.com/watch?v=1yejMVfmgyU
 - Event listing page: https://www.youtube.com/my_live_events?filter=scheduled
 - For participants:  https://hangouts.google.com/hangouts/_/ytl/nRYzQkG76Z_EvZuc2zdP0W3sB7lIZX4Nw9h8ID-zAX4=?eid=100598160817214911030&hl=en_US&authuser=0

  or try: https://hangouts.google.com/hangouts/_/g7ypqey6avdsvfpib2su67hebue

- Notes: https://docs.google.com/document/d/1d4-ygEkeshdQoJ46sbJdy_RflNJY2bKUM7G5NmRXhMg/edit

**Comment by sam-github** [comment]
I can't figure out how to get the doodle to work, or maybe @gibfahn you set it up wrong? It seems to give me only one option: March 28 - 31, TUE - FRI, 4:00 AM – 1:00 PM, and I have to accept that whole time. I'm free from 7am to 2pm PST wednesday, fwiw.

**Comment by gibfahn** [comment]
Hopefully fixed the doodle.

**Comment by MylesBorins** [comment]
Can confirm that doodle is fixed. My availability has been plugged in

**Comment by gibfahn** [comment]
I was obviously too optimistic with this doodle, should've included next week as well...

@jasnell could you plug in your availability for tomorrow? Looks like there should be a time that works there.

**Comment by gibfahn** [comment]
Okay, looks like the only time we can all make is today at 19:00-20:00 PM BST, a.k.a. 14:00PM-15:00PM EST. So let's meet then.

If someone more knowledgeable with Hangouts could set up a meeting link that'd be great. Not sure if we want to record or not.

See you there (looks like @addaleax will be joining too 😃  ).

**Comment by addaleax** [comment]
> looks like @addaleax will be joining too 😃 

If you don’t mind. ;) (Also, don’t be mad if I should not show up. I’ll try. :smile:)

**Comment by mhdawson** [comment]
I'll setup the hangout

**Comment by mhdawson** [comment]
Youtube for those who want to watch: https://www.youtube.com/watch?v=1yejMVfmgyU
event listing page: https://www.youtube.com/my_live_events?filter=scheduled
For participants:  Will add link just before meeting starts, so that we have option to record if appropriate.

**Comment by mhdawson** [comment]
participation link https://hangouts.google.com/hangouts/_/ytl/nRYzQkG76Z_EvZuc2zdP0W3sB7lIZX4Nw9h8ID-zAX4=?eid=100598160817214911030&hl=en_US&authuser=0

**Comment by jasnell** [comment]
That's 11am Pacific yes? Meeting now?

**Comment by gibfahn** [comment]
Yes

**Comment by jasnell** [comment]
I'm in the hangout but doesn't appear to be anyone else here

**Comment by gibfahn** [comment]
Strange, four of us here so far, maybe try again: https://hangouts.google.com/hangouts/_/ytl/nRYzQkG76Z_EvZuc2zdP0W3sB7lIZX4Nw9h8ID-zAX4=?eid=100598160817214911030&hl=en_US&authuser=0

**Comment by jasnell** [comment]
Still no go. Is it possible to send an invite from the hangout. To my gmail address

**Comment by gibfahn** [comment]
Sam just send you an email.

**Comment by sam-github** [comment]
I invited you from inside the hangout, @jasnell, did you get it? to jasnell@gmail.com?

**Comment by jasnell** [comment]
Right address but didn't receive any notification. Likely has something to do with being on mobile at the moment. The hangouts client on iPhone is... Lacking. Go on without me this time and I'll check the meeting notes when posted

**Comment by sam-github** [comment]
@jasnell try: https://hangouts.google.com/hangouts/_/g7ypqey6avdsvfpib2su67hebue

**Comment by sam-github** [comment]
And we might limp along without you, but without Myles, there is no point, we'll have to reschedule. We are  still pinging him, we'll give it a couple minutes.

**Comment by sam-github** [comment]
OK, new poll.... @jasnell can make next monday/tuesday, he's away after that.

**Comment by gibfahn** [comment]
New poll for Monday/Tuesday next week: https://beta.doodle.com/poll/6pea98peun636s6i

**Comment by gibfahn** [comment]
ping @jasnell @MylesBorins @addaleax (optional), please fill out the doodle.

**Comment by mhdawson** [comment]
Should there be a new doodle given that this week did not work out ?

**Comment by gibfahn** [comment]
Yep, so talked to @MylesBorins and he can't really do this week. I'll do a poll for next week.

Sorry for the excessive doodling.

**Comment by gibfahn** [comment]
Doodle poll v3, for Monday through Thursday of next week: http://doodle.com/poll/2i7i83h9vii9k7pu

**Comment by jasnell** [comment]
There does not appear to be a time zone selected in the doodle. I'm going to be in Ireland next week so my availability is going to be limited.

**Comment by gibfahn** [comment]
@jasnell it seems to be set to a London time zone, but I thought it would automatically change to your time zone. Quite possible I did something wrong.

![image](https://cloud.githubusercontent.com/assets/15943089/24656302/da5efdce-1939-11e7-8820-f8abc43675f8.png)

**Comment by sam-github** [comment]
Doodle displayed times in PST for me, seemed to be fine.

**Comment by gibfahn** [comment]
@jasnell @mhdawson @MylesBorins can you guys fill out the doodle?

http://doodle.com/poll/2i7i83h9vii9k7pu

**Comment by MylesBorins** [comment]
Done

**Comment by gibfahn** [comment]
Okay, final options chosen, 18:00-19:00 BST (should be 13:00-14:00 EST) .

**Comment by addaleax** [comment]
This is now, right? Does somebody have a hangout link?

**Comment by sam-github** [comment]
not sure. gibson is offline, not sure why. i'm trying to get him. we were chatting 30 mins ago.

**Comment by sam-github** [comment]
I'll try to setup a hangouts on air. Gibson was biking home, he is online and pinging @MylesBorins now

**Comment by sam-github** [comment]
https://hangouts.google.com/hangouts/_/mdk6v3wgf5cxlptxct7auynalye  <--- please join

**Comment by sam-github** [comment]
@addaleax we are waiting for you, joining?

**Comment by gibfahn** [comment]
Not able to stream due to technical difficulties, if anyone wants to join the hangout as an observer feel free.

**Comment by gibfahn** [comment]
Made the change to @evanlucas's PR here: https://github.com/nodejs/node/pull/11099#issuecomment-293672747

**Comment by jasnell** [comment]
Closing as this meeting is complete.
