### ISSUE TITLE
LTS meeting - missed

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#194]
Looks likes we missed the LTS meeting today.

Since Myles is traveling this week (I heard through the grapevine) I'd suggest we agree  to get together April 10 

@nodejs/LTS how does that sound ?

**Comment by gibfahn** [comment]
SGTM

**Comment by jasnell** [comment]
My availability on the 10th is going to be very limited. I'll likely have to miss if the meeting is on the 10th

**Comment by MylesBorins** [comment]
I can do the 10th as long as it is a bit earlier in the day... it is the first night of passover and I'm hosting a seder

**Comment by sam-github** [comment]
@jasnell @MylesBorins you two have the busy schedules, perhaps you can suggest days that are workable since the 10th sounds iffy? I'm basically available anytime 9-5 EST (except monday the 17th). Outside of that, early evenings are hard, but early mornings are OK.

**Comment by mhdawson** [comment]
@jasnell @MylesBorins Any suggestions on what times might work for you ? At this point I'm booked Monday/Tuesday.  Any Time Wed Thursday work for you 2 ?

**Comment by MylesBorins** [comment]
Should we perhaps wait until after back porting meeting and hold LTS meeting at next planned date?

**Comment by Fishrock123** [comment]
17th 9easter Monday) doesn't work as well as today (10th) or 24th for me.

**Comment by jasnell** [comment]
I've been traveling and haven't had a chance to look. I'll take a look at
the schedule tomorrow and will update my availability

**Comment by mhdawson** [comment]
I think as this point we just delay to the next scheduled time which is Apr 24th.
