### ISSUE TITLE
LTS schedule link broken by trailing 1

### ISSUE THREAD

**Issue by l2dy** [nodejs/LTS#197]
The link on https://nodejs.org/en/ points to https://github.com/nodejs/LTS#lts-schedule but the trailing `<sup>1</sup>` in README.md broke it (now https://github.com/nodejs/LTS#lts-schedule1).

**Comment by gibfahn** [comment]
Fixed in https://github.com/nodejs/nodejs.org/pull/1196 , should show up on the website soon.
