### ISSUE TITLE
Published or Release Build Feature for Node.js Web application

### ISSUE THREAD

**Issue by matt212** [nodejs/LTS#198]
Are there any npm packages for converting node.js web app's source code with all its dependencies within node_modules folder to compiled/released/published build files like for example :

- .net has .ddl file
- java has .jar file
- elixir has .beam file.

rather than any npm packages , any other alternatives to achieve the goal of published IL !

**Comment by gibfahn** [comment]
Can you raise this on https://github.com/nodejs/help ?

**Comment by matt212** [comment]
actually it should be a feature rather than some issue ! anyways will do the same .
thanks
