### ISSUE TITLE
LTS Meeting April 24th - 5 pm EST

### ISSUE THREAD

**Issue by gibfahn** [nodejs/LTS#201]
Feel free to edit if I messed it up.

## Present

@nodejs/lts

## When

9PM Monday April 24th UTC, or in your local timezone:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20170424T17&p1=179&ah=1

Previous meetings: https://github.com/nodejs/LTS/issues/194 https://github.com/nodejs/LTS/issues/185

## Where

Hangouts on Air:
- Observers: https://www.youtube.com/watch?v=CVPtof6dZLc
- Participants: https://hangouts.google.com/hangouts/_/ytl/9EDDsMjTm3qtKSlwGCeg8Pmasdbuo8UOT3DKbAxa5Zg=?eid=100598160817214911030&hl=en_US
- Events page: https://www.youtube.com/my_live_events

### nodejs/LTS
- Limit push access to LTS staging branches to backport team [#199](https://github.com/nodejs/LTS/issues/199)
- Node-v8 LTS support end on 2019-12-31 to meet EOSL of openssl-1.0.2 [#186](https://github.com/nodejs/LTS/issues/186)
- Backporting test fixes to maintenance branches [#205](https://github.com/nodejs/LTS/issues/205)
- Inspector - retain support for `--inspect --debug-brk` https://github.com/nodejs/node/issues/12364 (related: https://github.com/nodejs/node/pull/12615)
- Plan for triaging semver-minor backports in LTS meetings [#204](https://github.com/nodejs/LTS/issues/204)
- Potential Semver Minor Backports [#177](https://github.com/nodejs/LTS/issues/188)

### other

*Any questions in #node-dev on IRC or comments in this thread*

## Minutes

- doc: https://docs.google.com/document/d/1wyL9uQRJBSrUp4yD-bVIB51cRQQLOEbo9nRbz1O58nA/edit?usp=sharing

**Comment by refack** [comment]
I'd like to join the meeting (I promise to to quiet).
Also as I said in #203, I it be an honor for me to join the LTS effort

**Comment by gibfahn** [comment]
@refack FYI if you want to watch the meetings are all streamed live on Youtube. People do sometimes join "as observers" but I (personally) don't really know why that's done, WGs usually take questions (just post them in here).

**Comment by hbetts** [comment]
I really appreciate the live Youtube streaming, and the last meeting I took advantage of the `#node-dev` IRC channel to leave my own thoughts (wasn't sure whether there, or this GitHub issue, was more appropriate).

**Comment by MylesBorins** [comment]
Can we please include https://github.com/nodejs/LTS/issues/199

**Comment by mhdawson** [comment]
Link for participants: https://hangouts.google.com/hangouts/_/ytl/9EDDsMjTm3qtKSlwGCeg8Pmasdbuo8UOT3DKbAxa5Zg=?eid=100598160817214911030&hl=en_US

**Comment by refack** [comment]
+1 for no semver-minor (leave a window for an LTS WG consensus override vote)

**Comment by refack** [comment]
If you are reading me. I say remove `--inspect-brk`, it won't be adopted
Keep `--inspect-brk` permanently

**Comment by gibfahn** [comment]
>If you are reading me

We're reading you 😁

**Comment by refack** [comment]
I'm on it

**Comment by refack** [comment]
Uniform way to trigger debugger on first line #12630
