### ISSUE TITLE
Q2 2017 Boron (6.x) Release Schedule (Proposal)

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#206]
For Q2 of 2017 there will be an Active LTS release for Boron (6.x) on the first Tuesday of every month. A new r.c. will come out on the third Tuesday of each month.

Date | Release | Emoji
------------ | -------|------
May 2nd | v6.10.3 | 🚀
May 16th | v6.11.0-rc | 🐢
Jun 6th | v6.11.0 | 🎶

due to the month of May having 5 Tuesdays I've scheduled a minor release. This shortens the r.c. time to 3 weeks, we have traditionally done 4. I do not believe we will be assuming any extra risk and I find the schedule much easier to follow this way.

edit:

this schedule is currently a proposal and needs @nodejs/lts to review it first.

**Comment by jasnell** [comment]
A small tiny part of my brain now really wishes we would assign emoji's to each LTS release rather than codenames from the periodic table.

**Comment by jasnell** [comment]
This schedule LGTM

**Comment by gibfahn** [comment]
Schedule LGTM

**Comment by Fishrock123** [comment]
Schedule seems fine but I think specific emoji may just be more confusing that the numbers themselves.

**Comment by sam-github** [comment]
LGTM, will this go in the nodejs/LTS README?

I guess we don't need a 4.x release schedule because we intend to release now only on demand?

It would be nice to have a similar schedule for 7.x.

**Comment by MylesBorins** [comment]
Emojis were just meant to be fun... Not to be used during release. I can remove from initial comment

**Comment by MylesBorins** [comment]
We have generally kept these schedules in an issue.

Afaik there are no more planned v7 releases

We've only had a schedule like this for LTS

**Comment by evanlucas** [comment]
> Afaik there are no more planned v7 releases

There probably should be. There is a regression in v7.10.0 that has uncatchable errors in http.request(). I doubt I'll have the time this week, but I could probably cut on early next week

**Comment by mhdawson** [comment]
Schedule LGTM

**Comment by MylesBorins** [comment]
Unfortunately the v6.11.1-rc is delayed due to our tooling not working. Changes to github's abuse detection mechanism are stopping branch-diff from doing it's things.

I'm going to push to v6.11.1 release dates by one week to hopefully give us some time to figure this out

**Comment by MylesBorins** [comment]
v6.11.1 has been delay further due to security release. Expect a new schedule for the next quarter
