### ISSUE TITLE
openssl + node 8.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#207]
@shigeki @mhdawson I wanted to clarify reasoning for not moving to 1.1.x in Carbon

I believe the biggest reason was lack of fips support

https://wiki.openssl.org/index.php/FIPS_module_3.0

just wanted to make sure we are on the same page

**Comment by shigeki** [comment]
I did not know that page. I read the blog posts of https://www.openssl.org/blog/blog/2015/09/29/fips/ and https://www.openssl.org/blog/blog/2016/07/20/fips/. 

The current latest openssl-1.1.0 will be end of support in Aug. 2017 so FIPS support will be made in  the later version of openssl-1.1.x. I hope that the next release of 1.1.1 will become LTS and have FIPS support but it is not yet sure.

**Comment by mhdawson** [comment]
For me it was both the risk of making such a significant change so close to the release, and the lack of FIPS support as one of the concrete things we would lose.

**Comment by sam-github** [comment]
Note for posterity, Carbon is 8.x (I assume, its not listed on https://github.com/nodejs/LTS, but a "C" would be next).

**Comment by MylesBorins** [comment]
Thanks everyone. Makes perfect sense to hold off. Glad to have this thread for quick reference
