### ISSUE TITLE
npm: will we upgrade to npm3 in v0.12?

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#21]
I've had several independent inquiries on this: will v0.12 or pre-converged io.js upgrade to npm3 or will we hold off until the converged repo?

@nodejs/lts @nodejs/tsc

**Comment by Fishrock123** [comment]
Discussions in io.js seem to have indicated npm@3 should probably land in a major, and I am planning to see if it is reasonable to get it into 3.x.

See: https://github.com/nodejs/io.js/issues/942

**Comment by rvagg** [comment]
It'd be good to get an npm Inc POV on this. From the little feedback I've seen from users trying out 3.0, the changes seem to be enough to cause problems with certain workflows and the flattening of node_modules is showing up poor code that hardwires assumptions about the relative location of dependencies. So, I'd lean toward suggesting this would feel like a breaking change to some users and would be quite surprising in a patch upgrade, of 0.12 particularly.

**Comment by jasnell** [comment]
Linking this back to the main npm lts issue #14 and closing for now.
