### ISSUE TITLE
LTS Meeting May 15th - 5 pm EST

### ISSUE THREAD

**Issue by gibfahn** [nodejs/LTS#213]
## Present

@nodejs/lts

## When

9PM Monday May 15th UTC, or in your local timezone:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20170515T17&p1=179&ah=1

Previous meetings: https://github.com/nodejs/LTS/issues/201 https://github.com/nodejs/LTS/issues/194 https://github.com/nodejs/LTS/issues/185

## Where

Hangouts on Air:
- Observers: http://youtu.be/UFBMF9ndBDo
- Participants: https://hangouts.google.com/hangouts/_/ytl/HxsbrIwP9ZV5xVxteDdN2BkFNpTDkCZ12q6tgiVxRoc=?eid=100598160817214911030
- Events page: https://www.youtube.com/my_live_events

### nodejs/LTS
- meta: updated messaging regarding dates [#141](https://github.com/nodejs/LTS/pull/141)
- Clarify what happens with odd-numbered releases in April [#128](https://github.com/nodejs/LTS/pull/128)
- meta: charter the LTS Working Group [nodejs/CTC#122](https://github.com/nodejs/CTC/pull/122)
- Potential Semver Minor Backports [#177](https://github.com/nodejs/LTS/issues/188)

### other

*Any questions in #node-dev on IRC or comments in this thread*

## Minutes

- doc: https://docs.google.com/document/d/1KQmy29tP6AKBLiPSQ8ceKnYbD0jXwAwMKfECLXbm-yE/edit?usp=sharing

**Comment by sam-github** [comment]
@gibfahn  The time link points to the subject says May 15th, the body text says April 15th, and the timeanddate.com link points to May 10th :-)

**Comment by gibfahn** [comment]
@sam-github Should be fixed.

**Comment by mhdawson** [comment]
I'll be there

**Comment by MylesBorins** [comment]
Where's da link?

**Comment by mhdawson** [comment]
Added hangout links

**Comment by sam-github** [comment]
@nodejs/lts Meeting! Who's coming?
