### ISSUE TITLE
failures on aix v6.x-staging

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#218]
After landing libuv update we are seeing failures on aix during compilation

/cc @nodejs/platform-aix 

https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/5891/console

**Comment by MylesBorins** [comment]
we may need to land https://github.com/nodejs/node/pull/10085, but this is unrelated to the compiler failure

/cc @mhdawson

**Comment by MylesBorins** [comment]
It looks like the failure is specific to two member function not existing in v8::internal

```
../deps/v8/src/builtins/ppc/builtins-ppc.cc:672:76: error: no 'void v8::internal::Builtins::Generate_JSBuiltinsConstructStubForBase(v8::internal::MacroAssembler*)' member function declared in class 'v8::internal::Builtins'
 void Builtins::Generate_JSBuiltinsConstructStubForBase(MacroAssembler* masm) {
                                                                            ^
../deps/v8/src/builtins/ppc/builtins-ppc.cc:677:25: error: no 'void v8::internal::Builtins::Generate_JSBuiltinsConstructStubForDerived(v8::internal::MacroAssembler*)' member function declared in class 'v8::internal::Builtins'
     MacroAssembler* masm) {
                         ^
../deps/v8/src/builtins/ppc/builtins-ppc.cc: In static member function 'static void v8::internal::Builtins::Generate_CompileLazy(v8::internal::MacroAssembler*)':
../deps/v8/src/builtins/ppc/builtins-ppc.cc:1359:33: error: 'kOptimizedCodeMapOffset' is not a member of 'v8::internal::SharedFunctionInfo'
            FieldMemOperand(map, SharedFunctionInfo::kOptimizedCodeMapOffset));
```

**Comment by jeisinger** [comment]
that might be because the ppc port didn't yet port over https://chromium-review.googlesource.com/c/489525/

**Comment by rmcilroy** [comment]
Actually from looking at the errors I think it's because they've not yet ported over https://chromium-review.googlesource.com/c/500134/. They did port it over but reverted it when the original CL was reverted - shouldn't be too difficult to reland with the updates.

**Comment by jbajwa** [comment]
I'm working on porting to V8 master. I was wondering how it is affecting `v6.x-staging` branch where V8 is at 5.1 and the original CL was committed to V8 6.0 ?

**Comment by jbajwa** [comment]
The test job linked above seems to be from the canary branch,
```
Started by upstream project "node-test-commit-aix" build number 5891
originally caused by:
 Started by upstream project "node-test-commit-node-v8" build number 16
 originally caused by:
  Started by upstream project "node-update-v8-canary" build number 30
  originally caused by:
   Started by timer
```

**Comment by targos** [comment]
This failure is from the node-update-v8-canary job. It shouldn't be related to v6.x-staging.

**Comment by MylesBorins** [comment]
OH LOL... I messed that up This is unrelated to staging. Sorry for the fire drill 😄
