### ISSUE TITLE
Named LTS Releases

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#22]
Proposal: LTS Releases should be assigned a more user-friendly name *in addition to* the semantic versioning number.

@rvagg suggested drawing the names from the periodic table of elements (http://www.ptable.com/). For example: `Node.js 4.4.1 Hydrogen`. For each upcoming LTS release, the LTS WG would select a short list of candidate names and allow the community to vote on the name.

Other naming schemes are possible, and it's easy to bikeshed endlessly. Let's just pick one and go with it. I'm +1 on @rvagg's suggestion

/cc @cjihrig @nodejs/lts

**Comment by cjihrig** [comment]
I still think Mega Man bosses are better :-) but +1 to this.

**Comment by bnoordhuis** [comment]
I was going to suggest [Hadza](https://en.wikipedia.org/wiki/Hadza_language) words, but I can live with element names.  Will the half-life of the element reflect the support period?

**Comment by jasnell** [comment]
While using the half-life would be epic, that wouldn't work. The support period is the same for every release :-).  What would be even more fun is naming LTS updates that occur after various isotopes. Not sure how well that would work out tho in practice.

**Comment by trevnorris** [comment]
Don't know if I'd consider "Rutherfordium" or "Praseodymium" very "user-friendly" names. ;-P

TBH don't know if I've ever seen software that gives names in the LTS stage. Or, since I never use LTS anything, probably have and just don't know it.

**Comment by mhdawson** [comment]
+1 for element names

**Comment by Fishrock123** [comment]
is there a benefit to not just naming all majors?

**Comment by jasnell** [comment]
Naming all majors can cause confusion with users. Essentially, "All named releases are LTS. If there's no name, there's no LTS commitment".

**Comment by rvagg** [comment]
Where on earth did the Hadza suggestion come from @bnoordhuis? I hope that was a joke although it would be fun to see the confusion around "Node.js 4.0 qqeléko", "Node.js 8.3 nqokhóhii" and "Node.js 11.8 himiggêbee"

**Comment by jasnell** [comment]
It was decided on the last LTS WG call that we will have named LTS releases using the element names plan proposed by Rod (sorry @bnoordhuis , we can use Hadza for the next project we need codenames for)

**Comment by TooTallNate** [comment]
The "Chromium" LTS release will be interesting :stuck_out_tongue:
