### ISSUE TITLE
Update Node 8 schedule?

### ISSUE THREAD

**Issue by cjihrig** [nodejs/LTS#221]
For example, the Node 8 start date in schedule.json still says 2017-04-30

**Comment by hbetts** [comment]
@cjihrig would you be interested in submitting a pull request to update the date?

To others, how is the PNG image updated based on the contents of the JSON file?

**Comment by gibfahn** [comment]
>To others, how is the PNG image updated based on the contents of the JSON file?

It's currently done manually, usually by @rvagg [looking at the commit history](https://github.com/nodejs/LTS/commits/master/schedule.png). 

However, @cjihrig has written an npm module to update the graphic called [lts](https://www.npmjs.com/package/lts), so it'd be good if we could transition over to using that.
