### ISSUE TITLE
LTS Meeting June 5th - 5 pm EST

### ISSUE THREAD

**Issue by gibfahn** [nodejs/LTS#225]
## Present

@nodejs/lts, maybe @nodejs/release 

## When

9PM Monday May 15th UTC, or in your local timezone:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20170605T17&p1=179&ah=1

Previous meetings: https://github.com/nodejs/LTS/issues/213

## Where

Hangouts on Air:
- [Observers](https://www.youtube.com/watch?v=xSo6YiKzc5M)
- [Participants](https://hangouts.google.com/hangouts/_/ytl/0qRipO04v3I4lj52L0r4E9AyzWlhe5hTTmKgetCKqZU=?eid=100598160817214911030)
- [Events page](https://www.youtube.com/my_live_events)
- [Minutes](https://docs.google.com/document/d/1kb_LHdApG2VSNFm0IM4Gsdg5uDLYaqvNwrO3TwSexdA/edit?usp=sharing)

### nodejs/LTS

Chartering the Release Team as a Working Group [nodejs/CTC#123](https://github.com/nodejs/CTC/issues/123)

### other

*Any questions in #node-dev on IRC or comments in this thread*

**Comment by mhdawson** [comment]
Hangout for meeting https://hangouts.google.com/hangouts/_/ytl/0qRipO04v3I4lj52L0r4E9AyzWlhe5hTTmKgetCKqZU=?eid=100598160817214911030

**Comment by Fishrock123** [comment]
@mhdawson link is a 403

**Comment by gibfahn** [comment]
403 for me too

**Comment by mhdawson** [comment]
seems like Myles, James and Sam are in ? Did you use the link in the top or later ?

**Comment by Fishrock123** [comment]
@gibfahn I updated @mhdawson's comment to fix the link.

**Comment by gibfahn** [comment]
Opting to use the existing PR (https://github.com/nodejs/node/pull/13263) to discuss landing V8 5.9 with/without the patch rather than creating a new LTS issue.
