### ISSUE TITLE
should we unlabel backport-requested-v7.x PRs now?

### ISSUE THREAD

**Issue by sam-github** [nodejs/LTS#226]
At least one person backported a PR to 7.x because they saw the label, but they wasted their time, we aren't rereleasing 7.x, EDIT: https://github.com/nodejs/node/pull/13436#issuecomment-306006448  was the issue that made me thing this may be a problem.

I went through the first 6 or 8 PRs in https://github.com/nodejs/node/issues?q=label%3Abackport-requested-v7.x, and AFAICT they are all in 8.x, so I removed the label.

I can keep going, but I don't think its necessary. If any PRs are missing from 8.x, that will be dealt with by the 8.x release team, so I think we can uniformly unlabel all the issues with `backport-requested-v7.x` to prevent anyone wasting their time trying to backport.

Agreed, @nodejs/lts?

**Comment by jasnell** [comment]
It's still possible that we could do a 7.x release sometime this month... not *likely* but *possible*. I'd suggest waiting until the end of June

**Comment by sam-github** [comment]
We might, but we would only include really critical bug fixes in it, right? Whereas the things still labelled `backport-requested-7.x` were clearly not that important, or they would have been backported already.

I'm just trying to avoid any more people wasting their time: https://github.com/nodejs/node/pull/13436#issuecomment-306006448

**Comment by gibfahn** [comment]
+1 to removing it from existing PRs. If any of them were urgent enough to trigger a v7.x release that would already have happened. If something urgent comes up and we have to do a v7.x release, we can tag that PR then (we don't have to delete the tag).

If we do another v7.x release, is there any reason to backport [these 32 PRs](https://github.com/nodejs/node/pulls?utf8=%E2%9C%93&q=label%3Abackport-requested-v7.x%20) to it?

**Comment by mhdawson** [comment]
I think we should either remove (my first choice) or it we leave it on maybe add a comment explaining the situation so people don't do unnecessary work.  I would not be happy if I did a backport only to be told it was not going to be accepted.

**Comment by gibfahn** [comment]
I think this can be closed as agreed (if anyone has an issue with this feel free to reopen).

**Comment by gibfahn** [comment]
Unlabelled everything.
