### ISSUE TITLE
What nightlies to release?

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/LTS#229]
@nodejs/lts @nodejs/build 

Currently we are releasing nightlies from the `master` and `v8.x` branches (`v6.x` and `v7.x` were there until recently). While `master` is correct, for the LTS branches shouldn't we release nightles from the `v*.x-staging` branches instead?

The last nightlies for v6 seem to match the last v6 releases exactly (plus the "working on next version" commit).

Also, should we release nightlies of all LTS branches or just `v8.x`?

**Comment by MylesBorins** [comment]
we could do nightlies of the the staging branches but I'm not currently convinced it is entirely necessary. We often only audit commits before a release, and at that point we are already preparing the R.C.

I for one would say that we don't need nightlies for LTS

**Comment by joaocgreis** [comment]
Thanks, that makes sense.

@MylesBorins @jasnell what about v8.x? Should we have nothing, `v8.x-staging` or `v8.x`?

**Comment by MylesBorins** [comment]
While 8 is in Current we should do nightlies from 8.x-staging

8.x will always be aligned with the release

**Comment by joaocgreis** [comment]
Updated the branch in the server, next nightlies should come out of staging. Thanks!
