### ISSUE TITLE
LTS Meeting June 26th - 5 pm EST

### ISSUE THREAD

**Issue by gibfahn** [nodejs/LTS#233]
## Present

@nodejs/lts, maybe @nodejs/release if they're interested

## When

9PM Monday May 15th UTC, or in your local timezone:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20170626T17&p1=179&ah=1

Previous meetings: https://github.com/nodejs/LTS/issues/225

## Where

Hangouts on Air:
- [Observers](https://www.youtube.com/watch?v=XubwojXZGtU)
- [Participants] (https://hangouts.google.com/hangouts/_/ytl/FcgwTFuBbVPgqYyk_hSRjhUJG8ZPjn6IaWBVjStt37g=?eid=100598160817214911030)
- [Events page](https://www.youtube.com/my_live_events)
- [Minutes](https://docs.google.com/document/d/16c_FvWTi-IJ-gZkjfo_eQtIOyRpgpGRUGTq2re3CnGs/edit?usp=sharing)

### nodejs/LTS

[CTC `lts-agenda` issues](https://github.com/nodejs/CTC/issues?q=is%3Aopen+is%3Aissue+label%3Alts-agenda) and [LTS `lts-agenda` issues](https://github.com/nodejs/LTS/issues?q=is%3Aopen+is%3Aissue+label%3Alts-agenda)

Chartering the Release Team as a Working Group [nodejs/CTC#123](https://github.com/nodejs/CTC/issues/123)

### other

*Any questions in #node-dev on IRC or comments in this thread*

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by mhdawson** [comment]
meeting link for participants. https://hangouts.google.com/hangouts/_/ytl/FcgwTFuBbVPgqYyk_hSRjhUJG8ZPjn6IaWBVjStt37g=?eid=100598160817214911030

**Comment by gibfahn** [comment]
Minutes: https://github.com/nodejs/LTS/pull/234
