### ISSUE TITLE
LTS WG Meeting 17 July 2017

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#235]
I see by the schedule the meeting is set for today.  @gibfahn has been raising the issues lately but he is on vacation for a few weeks so I'm opening this one now (better late than never).

## Present

@nodejs/lts, maybe @nodejs/release if they're interested

## When

9PM Monday July 17th UTC, or in your local timezone:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20170626T17&p1=179&ah=1

Previous meetings: https://github.com/nodejs/LTS/issues/233

## Where

Hangouts on Air:
- [Observers](https://www.youtube.com/watch?v=qFCsn63CV2A)
- [Participants] (will be added a few minutes before meeting starts)
- [Events page](https://www.youtube.com/my_live_events)
- [Minutes](https://docs.google.com/document/d/1FP6Lkb8zPbVBdWoGPF_wVee8L6TzlMYrxptoGJELe7A/edit?usp=sharing)

### nodejs/node

* CI: test with `--with-snapshot` on the slower platforms [#14222](https://github.com/nodejs/node/issues/14222)
* tracking issue: full VS2017 support [#13052](https://github.com/nodejs/node/issues/13052)
* (v6.x backport) src: allow CLI args in env with NODE_OPTIONS [#12677](https://github.com/nodejs/node/pull/12677)
* inspector: enable --inspect-brk in v6 [#12615](https://github.com/nodejs/node/pull/12615)
* Remove `indexOf` usage from tests in favor of `includes` [#12586](https://github.com/nodejs/node/issues/12586)

### nodejs/LTS

* doc: charter the Release working group [#223](https://github.com/nodejs/LTS/pull/223)

### nodejs/CTC

* Chartering the Release Team as a Working Group [#123](https://github.com/nodejs/CTC/issues/123)
* meta: charter the LTS Working Group [#122](https://github.com/nodejs/CTC/pull/122)

*Any questions in #node-dev on IRC or comments in this thread*

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by MylesBorins** [comment]
Most of those issues are voting on semver minor changes

I'm going to suggest we skip this week if no one is opposed

**Comment by sam-github** [comment]
I can make the time, but skipping seems reasonable, if we all comment on those issues in github.

**Comment by mhdawson** [comment]
I'd really like to get to closure on https://github.com/nodejs/LTS/pull/223 if we are agreed that we are ready to go module last remaining nits, I think we can cancel, otherwise I think we should have a conversation in the meeting to get agreement on what else needs to change.

**Comment by sam-github** [comment]
I don't have any comment on #223, it LGTM. Though I don't understand why every WG needs to rediscuss the boilerplate (CONTRIBUTING.md, etc), it seems like they should be the same for all WGs. If all the comments have been addressed, can't it just be landed?

**Comment by MylesBorins** [comment]
I've just put my notes on #223 
Overall looks v good, just a handful of nits. I don't think having the meeting is going to help flesh it out any further than it currently is... but more than happy to attend

**Comment by mhdawson** [comment]
@MylesBorins thanks, I'll push an update to address the new comments and then I'd like to add to the agenda for the CI.

I'll cancel the meeting for today.
