### ISSUE TITLE
Meeting Aug 28th, 2017

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#243]
The Node.js google calendar shows a meeting for today at 5 EST.

I know Myles is away.  

These are on the agenda:

## Present

@nodejs/lts, maybe @nodejs/release if they're interested

## When

- 9PM Monday August 28th UTC, or [in your local timezone](
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+LTS+Working+Group+Meeting&iso=20170828T21)
- Previous meetings: https://github.com/nodejs/LTS/issues/235

## Where

Hangouts on Air:
- [Observers]
- [Participants]
- [Events page](https://www.youtube.com/my_live_events)
- [Minutes](https://docs.google.com/document/d/1b1GTR8PUgQ0lgXPqzoOF7HRbyR3k6iSpz_16tEA6cYI/edit?usp=sharing)

### nodejs/LTS

[CTC `lts-agenda` issues](https://github.com/nodejs/CTC/issues?q=is%3Aopen+is%3Aissue+label%3Alts-agenda) and [LTS `lts-agenda` issues](https://github.com/nodejs/LTS/issues?q=is%3Aopen+is%3Aissue+label%3Alts-agenda)

### nodejs/node

* (v6.x backport) process: add --redirect-warnings command line argument [#14480](https://github.com/nodejs/node/pull/14480)
* \[v6.x backport\] doc,assert: document stackStartFunction in fail [#14427](https://github.com/nodejs/node/pull/14427)
* CI: test with `--with-snapshot` on the slower platforms [#14222](https://github.com/nodejs/node/issues/14222)
* tracking issue: full VS2017 support [#13052](https://github.com/nodejs/node/issues/13052)
* (v6.x backport) src: allow CLI args in env with NODE_OPTIONS [#12677](https://github.com/nodejs/node/pull/12677)
* inspector: enable --inspect-brk in v6 [#12615](https://github.com/nodejs/node/pull/12615)
* Remove `indexOf` usage from tests in favor of `includes` [#12586](https://github.com/nodejs/node/issues/12586)

### other

*Any questions in #node-dev on IRC or comments in this thread*

@nodejs/lts Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by rvagg** [comment]
Won't be able to make it. Need more sleep atm and this meeting is early morning for me. Nothing in this list looks particularly controversial but I'll try and follow up in the individual issues as soon as I have a bit of time.

**Comment by mhdawson** [comment]
@gibfahn @sam-github can one of you volunteer to fill out the meeting issues/notes etc.

**Comment by gibfahn** [comment]
>@gibfahn @sam-github can one of you volunteer to fill out the meeting issues/notes etc.

Sure, I can do that.

**Comment by sam-github** [comment]
@mhdawson you setting up a  link?

**Comment by gibfahn** [comment]
Looks like we're not having this one.

**Comment by mhdawson** [comment]
Sorry all of the goings on distracted me.

**Comment by sam-github** [comment]
Lots of distraction, and lots of vacation, better to have it with more quorum on another week.
