### ISSUE TITLE
V8 maintainer skills

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/LTS#28]
Here is my thinking of what we should look for in a potential V8 maintainer:
- Strong C++ and x86/x86_64 assembly skills.
- Familiar with VM technology (pre if they've worked on Hotspot.)
- Experience with Win32 and POSIX application development.
- Experience working with large code bases.
- Background in application security preferable.
- Self-directed.

I can help with on-boarding, high-level concepts, bird's eye view of the code base, etc.

**Comment by mikeal** [comment]
Are we looking to try and recruit someone full time or are we looking to attract a number of people, on-board them, and hope a few stick around?

Additionally, @littledan is on the v8 team in San Francisco and has been reaching out to offer help/support :)

**Comment by bnoordhuis** [comment]
I think it would have to be a paid position.  It's a long-term commitment, work-intensive and unglorious.  Retaining volunteers would be hard.

**Comment by mhdawson** [comment]
+1 on ben's comment.

**Comment by thefourtheye** [comment]
If it's okay, can volunteers attend the onboarding? I always wanted to get the basic insights of v8 also. Apart from that, having more people trained is good in the long run, right?

**Comment by bnoordhuis** [comment]
@thefourtheye You're welcome to but I don't think it's going to be a single one-hour session.  If you have V8-related questions, by all means ping me in #io.js or #v8 on freenode.

**Comment by thefourtheye** [comment]
@bnoordhuis Thanks Ben :-)

**Comment by littledan** [comment]
Happy to help any way I can. I'm new to the V8 team so I don't know all the details of internals (I'm on the language team so I've been learning about the frontend and standard library), but let me know if I can help somehow. Happy to meet up some time if anyone is in the Bay Area, and I'm on #v8.

**Comment by indutny** [comment]
I'm not sure if qualify for this, but I think there was several people who was already on it. Does it require any special qualities that I do not posses yet? ;)

**Comment by bnoordhuis** [comment]
@indutny Dedication to the job. :-)

You would have to commit to $x hours for the indefinite future (i.e., years), where $x is on the order of 0.25 to 0.5 FTE, maybe more.

**Comment by indutny** [comment]
If you say so... ok :)

**Comment by rgbkrk** [comment]
While I'm not in any capacity handle this role, I'd love to work towards this knowledge and background. `NAN` is pretty darn important and I'd love to more deeply understand and resolve issues related to native packages in node across node, iojs, Electron, and Atom (particularly `node-zmq`).

**Comment by bnoordhuis** [comment]
@rgbkrk If you want to get involved, nan and node-gyp could use more eyeballs, both on the source and open pull requests.  I was informed yesterday that node-gyp has zero test coverage so if you want, you have your work cut out for you.

If you have questions or just want to chat, you can find us in #io.js on freenode.net.

**Comment by TheAlphaNerd** [comment]
We seem to have a pretty good pace going with backporting V8 stuff at the moment. Closing for now, please feel free to reopen if I did so prematurely
