### ISSUE TITLE
Status of v0.8.x?

### ISSUE THREAD

**Issue by chorrell** [nodejs/LTS#30]
Hi!

Apologies if this has already been covered elsewhere. I'm going on the assumption that support (e.g., security fixes) for v0.8.x will be dropped (unless that's happened already?) I can't find any explicit statement about this anywhere, but it seems to be the case and it's not included as an LTS release (which is good!).

I'm asking because I want to know if and when I can stop including a v0.8.x in the Docker node image (https://github.com/joyent/docker-node/issues/34). It should be noted that once dropped, users would still be able to pull a node v0.8.x image from the registry (e.g, `docker pull node:0.8.28` or `docker pull node:0.8`) there just won't be any 0.8 updates once I drop it from the GitHub repo.

**Comment by bnoordhuis** [comment]
> I'm going on the assumption that support (e.g., security fixes) for v0.8.x will be dropped (unless that's happened already?)

I believe that's the case, the last v0.8 release was over a year ago.  v0.8 wasn't discussed in any of the LTS discussions either, as far as I'm aware.

**Comment by Fishrock123** [comment]
Yeah, as far as I am aware 0.8 had already been put to rest once 0.12 came out.

**Comment by chorrell** [comment]
OK cool. I'll make plans to eventually drop if from the docker-node image.

Thanks!
