### ISSUE TITLE
LTS documentation on nodejs.org

### ISSUE THREAD

**Issue by phillipj** [nodejs/LTS#44]
Do you have any thoughts on documenting LTS on nodejs.org? As soon as v4 LTS and v5 has been released, I think we should at least have an LTS section on the [downloads page](https://nodejs.org/en/download/) documenting what LTS means alongside the LTS release schedule plan graphics. Maybe even pros / cons lists for both v4 and v5.

Appreciate all the help we can get on this while preparing nodejs.org for these two release lines in https://github.com/nodejs/new.nodejs.org/issues/200.

**Comment by Fishrock123** [comment]
LTS should probably have links to it's documentation, yes.

**Comment by rvagg** [comment]
@Fishrock123 I think this is about how we should document LTS & what the pros and cons are for various use-cases. We should come up with some text to provide the website WG. Anyone have time to strawman this so we can iterate with the website team to find the right balance of size and information?
