### ISSUE TITLE
LTS Release Best Practices

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#46]
Will use this issue to begin tracking best practices procedures for LTS releases. There are a few good post mortem lessons learned from cutting the first one:

* For the initial v4.2.0 cut, because we did not have another stable yet (v5.x), I was a bit more relaxed about landing changes. Unfortunately, those ended up leading to some critical regressions that would have been caught had the change first gone out in either a nightly from master or a stable release. From this point on, I strongly recommend that, with exception to critical security and bug fixes, we do not land any code changes in LTS that have not landed in at least one nightly or stable.

* We seriously need better ecosystem tests. It's time to keep iterating on citgm.

(will add more as we go)

**Comment by mhdawson** [comment]
Agreed on both points.  I'd also add that we should get more conservative over time for a particular LTS release.  At some point in the lifecycle for each LTS release we should get to the point there is a good reason for a PR to be pulled over to that LTS release (for example a user actually reported an issue on that LTS release) as opposed to pulling over everything that is available.

**Comment by jasnell** [comment]
3. It's going to be difficult to keep track of issues / PRs that need to be pulled back to v4.x. I've added a new `lts-watch-v4.x` label that should be applied to issues and PRs that need to be tracked and considered for landing in v4.x
