### ISSUE TITLE
LTS Meeting 2015-10-19

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#47]
@nodejs/lts ... putting out the call for agenda items now!

Time: 8PM Monday October 19th UTC (1pm Pacific), or in your local timezone: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js%20Foundation%20LTS%20Meeting%202015-10-19&iso=20151019T20 **PLEASE NOTE DAYLIGHT SAVING SHIFT FOR SOME TIMEZONES**

**Agenda and minutes** can be collected in here and copied into this repo later: https://docs.google.com/document/d/156bztXDR1CoPAU8BzCKCbgU-9IYTprk__aNsd0N1G0Q (if you're attending the meeting and don't have write access to this doc please give me your google login email).

Previous minutes: https://docs.google.com/document/d/1DOcI2B8F0nuoz2hf6uidCrAG0N067YEAR192ljguJhc/edit#

**Hangout on air** for active participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYe1gWyx4ZbW2Uyl4oVBMn2ZgRw_viokqpxw5gjFHwnkJr9rfw

**YouTube** feed for observers and saved recording: http://www.youtube.com/watch?v=wfg2nHXAQqI

Current invited participants, this list is not exclusive if you think you should also join:

* @bnoordhuis 
* @dshaw
* @Fishrock123 
* @jasnell 
* @misterdjules 
* @rvagg
* @shigeki
* @trevnorris 
* @geek 
* @mhdawson
* @ofrobots
* @joaocgreis
* @srl295
* @zkat

Agenda discussion can happen in this thread.

**Comment by jasnell** [comment]
Had a calendar snafu... will be there shortly

**Comment by Fishrock123** [comment]
Oops. Not used to Eastern Time yet.

**Comment by bnoordhuis** [comment]
Was an invite sent out for this?  I didn't have it on my calendar.

**Comment by misterdjules** [comment]
I had created the original Google calendar entry, and it seems I inadvertently removed that entry from my calendar. My apologies for the confusion. If a calendar entry is useful, then I'd suggest creating a new one.
