### ISSUE TITLE
LTS WG Meeting - 2015-11-16 1pm Pacific Time

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#56]
## Invited:

@nodejs/lts WG members

### Participation

Google Hangouts on Air for Participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYfIcvFeHfG5pcWDl9DmR4kXlcLfoEcFiSHdRKxhKcfkJQEELQ

For observers: https://plus.google.com/events/c2i68prcaqmcqjjsavusm4k12b4

### nodejs/LTS

* Charter this [#48](https://github.com/nodejs/LTS/issues/48)
* Schedule for v0.10.x and v0.12.x Releases [#52](https://github.com/nodejs/LTS/issues/52)
* tls: make server not use DHE in less than 1014 bits [#49](https://github.com/nodejs/LTS/issues/49)

### nodejs/node

* Feature/clang format [#3612](https://github.com/nodejs/node/pull/3612)

**Comment by zkat** [comment]
I'm gonna miss this one :(

**Comment by jasnell** [comment]
Only @mhdawson and I showed. We assigned all work items randomly to those who didn't show ;-) 
Will reschedule for next week

**Comment by bnoordhuis** [comment]
@jasnell Can you send out email invites?  I always miss this one because it's not on my calendar.
