### ISSUE TITLE
v4.2.2+1 commit candidates

### ISSUE THREAD

**Issue by rvagg** [nodejs/LTS#57]
Thanks to @thealphanerd for a champion effort in merging a bunch of commits in to `v4.x-staging` we now have a pretty good list to look at and discuss whether there's anything we might consider inappropriate for the next LTS release. I believe that all of these commits fall after `v5.0.0` so have not been included in a stable release yet so they still have that hurdle to go through. The important part is the discussion so we can further refine our criteria for what should make it in to LTS and what shouldn't. So if anything in this list stands out as a potential concern then please raise it for discussion. @thealphanerd perhaps you can fill us in on any borderline commits that didn't make it but may be worth discussing?

`branch-diff v4.x v4.x-staging --group`

* [[`935b8be8f6`](https://github.com/nodejs/node/commit/935b8be8f6)] - Add missing va_end before return (Ömer Fadıl Usta) [#3565](https://github.com/nodejs/node/pull/3565)
* [[`aef3d549af`](https://github.com/nodejs/node/commit/aef3d549af)] - **build**: fix configuring with prebuilt libraries (Markus Tzoe) [#3135](https://github.com/nodejs/node/pull/3135)
* [[`e86817cf81`](https://github.com/nodejs/node/commit/e86817cf81)] - **cluster**: send suicide message on disconnect (cjihrig) [#3720](https://github.com/nodejs/node/pull/3720)
* [[`c37a560df4`](https://github.com/nodejs/node/commit/c37a560df4)] - **crypto**: Improve error checking and reporting (Stefan Budeanu) [#3753](https://github.com/nodejs/node/pull/3753)
* [[`44d4a02694`](https://github.com/nodejs/node/commit/44d4a02694)] - **deps**: upgrade npm to 2.14.9 (Forrest L Norvell) [#3686](https://github.com/nodejs/node/pull/3686)
* [[`a632db5ba6`](https://github.com/nodejs/node/commit/a632db5ba6)] - **dns**: prevent undefined values in results (Junliang Yan) [#3696](https://github.com/nodejs/node/pull/3696)
* [[`877d86d32d`](https://github.com/nodejs/node/commit/877d86d32d)] - **doc**: add link to \[customizing util.inspect colors\]. (Jesse McCarthy) [#3749](https://github.com/nodejs/node/pull/3749)
* [[`65267bcdec`](https://github.com/nodejs/node/commit/65267bcdec)] - **doc**: sort tls alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`46356965ff`](https://github.com/nodejs/node/commit/46356965ff)] - **doc**: sort stream alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`600bc56561`](https://github.com/nodejs/node/commit/600bc56561)] - **doc**: sort net alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`256467208e`](https://github.com/nodejs/node/commit/256467208e)] - **doc**: sort process alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`e6704393f6`](https://github.com/nodejs/node/commit/e6704393f6)] - **doc**: sort zlib alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`57f298f482`](https://github.com/nodejs/node/commit/57f298f482)] - **doc**: sort util alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`cb62bb2a1b`](https://github.com/nodejs/node/commit/cb62bb2a1b)] - **doc**: sort https alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`2cac10d9c0`](https://github.com/nodejs/node/commit/2cac10d9c0)] - **doc**: sort http alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`133f84e352`](https://github.com/nodejs/node/commit/133f84e352)] - **doc**: sort modules alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`fdeaec50d3`](https://github.com/nodejs/node/commit/fdeaec50d3)] - **doc**: sort readline alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`45f7d75c61`](https://github.com/nodejs/node/commit/45f7d75c61)] - **doc**: sort repl alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`babc561cbf`](https://github.com/nodejs/node/commit/babc561cbf)] - **doc**: sort string_decoder alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`cf96a53520`](https://github.com/nodejs/node/commit/cf96a53520)] - **doc**: sort timers alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`ea66bd3a54`](https://github.com/nodejs/node/commit/ea66bd3a54)] - **doc**: sort tty alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`fd2e926313`](https://github.com/nodejs/node/commit/fd2e926313)] - **doc**: sort url alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`0814b8c0c9`](https://github.com/nodejs/node/commit/0814b8c0c9)] - **doc**: sort vm alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`d7b685c63f`](https://github.com/nodejs/node/commit/d7b685c63f)] - **doc**: sort querystring alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`84b9376b45`](https://github.com/nodejs/node/commit/84b9376b45)] - **doc**: sort punycode alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`78277495df`](https://github.com/nodejs/node/commit/78277495df)] - **doc**: sort path alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`bbd00ee296`](https://github.com/nodejs/node/commit/bbd00ee296)] - **doc**: sort os alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`806b6944fc`](https://github.com/nodejs/node/commit/806b6944fc)] - **doc**: sort globals alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`fc346fb209`](https://github.com/nodejs/node/commit/fc346fb209)] - **doc**: sort fs alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`1f644b1b5a`](https://github.com/nodejs/node/commit/1f644b1b5a)] - **doc**: sort events alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`c8ba5570d9`](https://github.com/nodejs/node/commit/c8ba5570d9)] - **doc**: sort errors alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`128d100a0a`](https://github.com/nodejs/node/commit/128d100a0a)] - **doc**: sort dgram alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`ecfbbf0fb9`](https://github.com/nodejs/node/commit/ecfbbf0fb9)] - **doc**: sort crypto alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`720f068637`](https://github.com/nodejs/node/commit/720f068637)] - **doc**: sort dns alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`1b668b5ce3`](https://github.com/nodejs/node/commit/1b668b5ce3)] - **doc**: sort console alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`448523636a`](https://github.com/nodejs/node/commit/448523636a)] - **doc**: sort cluster alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`2c5e7ede79`](https://github.com/nodejs/node/commit/2c5e7ede79)] - **doc**: sort child_process alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`2433e3de96`](https://github.com/nodejs/node/commit/2433e3de96)] - **doc**: sort buffer alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`2f8caaf756`](https://github.com/nodejs/node/commit/2f8caaf756)] - **doc**: sort assert alphabetically (Tristian Flanagan) [#3662](https://github.com/nodejs/node/pull/3662)
* [[`8b6120d84f`](https://github.com/nodejs/node/commit/8b6120d84f)] - **doc**: add note on tls connection meta data methods (Tyler Henkel) [#3746](https://github.com/nodejs/node/pull/3746)
* [[`3435f87613`](https://github.com/nodejs/node/commit/3435f87613)] - **doc**: add note to util.isBuffer (Evan Lucas) [#3790](https://github.com/nodejs/node/pull/3790)
* [[`a49dd8913c`](https://github.com/nodejs/node/commit/a49dd8913c)] - **doc**: add romankl to collaborators (Roman Klauke) [#3725](https://github.com/nodejs/node/pull/3725)
* [[`5cbfb76919`](https://github.com/nodejs/node/commit/5cbfb76919)] - **doc**: add saghul as a collaborator (Saúl Ibarra Corretgé)
* [[`64e6d06ad7`](https://github.com/nodejs/node/commit/64e6d06ad7)] - **doc**: add thealphanerd to collaborators (Myles Borins) [#3723](https://github.com/nodejs/node/pull/3723)
* [[`9970b76623`](https://github.com/nodejs/node/commit/9970b76623)] - **doc**: update lts description in the collaborator guide (James M Snell) [#3668](https://github.com/nodejs/node/pull/3668)
* [[`9ce1f75cb7`](https://github.com/nodejs/node/commit/9ce1f75cb7)] - **doc**: add LTS info to COLLABORATOR_GUIDE.md (Myles Borins) [#3442](https://github.com/nodejs/node/pull/3442)
* [[`d7b4f759c5`](https://github.com/nodejs/node/commit/d7b4f759c5)] - **doc**: typo fix in readme.md (Sam P Gallagher-Bishop) [#3649](https://github.com/nodejs/node/pull/3649)
* [[`d410d5856d`](https://github.com/nodejs/node/commit/d410d5856d)] - **doc**: fix wrong date and known issue in changelog.md (James M Snell) [#3650](https://github.com/nodejs/node/pull/3650)
* [[`5a23bb59ef`](https://github.com/nodejs/node/commit/5a23bb59ef)] - **doc**: rename iojs-* groups to nodejs-* (Steven R. Loomis) [#3634](https://github.com/nodejs/node/pull/3634)
* [[`b3b55a5155`](https://github.com/nodejs/node/commit/b3b55a5155)] - **doc**: fix crypto spkac function descriptions (Jason Gerfen) [#3614](https://github.com/nodejs/node/pull/3614)
* [[`bb20abb320`](https://github.com/nodejs/node/commit/bb20abb320)] - **doc**: Updated streams simplified constructor API (Tom Gallacher) [#3602](https://github.com/nodejs/node/pull/3602)
* [[`08ab9f35da`](https://github.com/nodejs/node/commit/08ab9f35da)] - **doc**: made code spans more visible in the API docs (phijohns) [#3573](https://github.com/nodejs/node/pull/3573)
* [[`98762d2ae1`](https://github.com/nodejs/node/commit/98762d2ae1)] - **doc**: added what buf.copy returns (Manuel B) [#3555](https://github.com/nodejs/node/pull/3555)
* [[`dfc2707097`](https://github.com/nodejs/node/commit/dfc2707097)] - **doc**: fix function param order in assert doc (David Woods) [#3533](https://github.com/nodejs/node/pull/3533)
* [[`d02365ba83`](https://github.com/nodejs/node/commit/d02365ba83)] - **doc**: add note about timeout delay > TIMEOUT_MAX (Guilherme Souza) [#3512](https://github.com/nodejs/node/pull/3512)
* [[`4a94c0a06f`](https://github.com/nodejs/node/commit/4a94c0a06f)] - **doc**: add caveats of algs and key size in crypto (Shigeki Ohtsu) [#3479](https://github.com/nodejs/node/pull/3479)
* [[`22bfe2297b`](https://github.com/nodejs/node/commit/22bfe2297b)] - **doc**: add method links in events.markdown (Alejandro Oviedo) [#3187](https://github.com/nodejs/node/pull/3187)
* [[`38a5ae1285`](https://github.com/nodejs/node/commit/38a5ae1285)] - **doc**: stdout/stderr can block when directed to file (Ben Noordhuis) [#3170](https://github.com/nodejs/node/pull/3170)
* [[`5689630c84`](https://github.com/nodejs/node/commit/5689630c84)] - **docs**: fs - change links to buffer encoding to Buffer class anchor (fansworld-claudio) [#2796](https://github.com/nodejs/node/pull/2796)
* [[`948af717d5`](https://github.com/nodejs/node/commit/948af717d5)] - **module**: remove unnecessary JSON.stringify (Andres Suarez) [#3578](https://github.com/nodejs/node/pull/3578)
* [[`486d287c1e`](https://github.com/nodejs/node/commit/486d287c1e)] - **repl**: don't crash if cannot open history file (Evan Lucas) [#3630](https://github.com/nodejs/node/pull/3630)
* [[`bf489691be`](https://github.com/nodejs/node/commit/bf489691be)] - **repl**: To exit, press ^C again or type .exit. (Hemanth.HM) [#3368](https://github.com/nodejs/node/pull/3368)
* [[`550c606428`](https://github.com/nodejs/node/commit/550c606428)] - **src**: Revert "nix stdin _readableState.reading" (Roman Reiss) [#3490](https://github.com/nodejs/node/pull/3490)
* [[`07b57914e4`](https://github.com/nodejs/node/commit/07b57914e4)] - **test**: use really invalid hostname (Sakthipriyan Vairamani) [#3711](https://github.com/nodejs/node/pull/3711)
* [[`0fb40b4300`](https://github.com/nodejs/node/commit/0fb40b4300)] - **test**: Fix test-cluster-worker-exit.js for AIX (Imran Iqbal) [#3666](https://github.com/nodejs/node/pull/3666)
* [[`2570cb79e5`](https://github.com/nodejs/node/commit/2570cb79e5)] - **test**: fix test-module-loading-error for musl (Hugues Malphettes) [#3657](https://github.com/nodejs/node/pull/3657)
* [[`7009e019af`](https://github.com/nodejs/node/commit/7009e019af)] - **test**: fix test-net-persistent-keepalive for AIX (Imran Iqbal) [#3646](https://github.com/nodejs/node/pull/3646)
* [[`c10f17fafd`](https://github.com/nodejs/node/commit/c10f17fafd)] - **test**: fix path to module for repl test on Windows (Michael Cornacchia) [#3608](https://github.com/nodejs/node/pull/3608)
* [[`84f8eb7094`](https://github.com/nodejs/node/commit/84f8eb7094)] - **test**: add test-zlib-flush-drain (Myles Borins) [#3534](https://github.com/nodejs/node/pull/3534)
* [[`75b4613f46`](https://github.com/nodejs/node/commit/75b4613f46)] - **test**: enhance fs-watch-recursive test (Sakthipriyan Vairamani) [#2599](https://github.com/nodejs/node/pull/2599)
* [[`1064eb6aa8`](https://github.com/nodejs/node/commit/1064eb6aa8)] - **util**: use regexp instead of str.replace().join() (qinjia) [#3689](https://github.com/nodejs/node/pull/3689)
* [[`1543c78c12`](https://github.com/nodejs/node/commit/1543c78c12)] - **zlib**: only apply drain listener if given callback (Craig Cavalier) [#3534](https://github.com/nodejs/node/pull/3534)
* [[`d1cedbd981`](https://github.com/nodejs/node/commit/d1cedbd981)] - **zlib**: pass kind to recursive calls to flush (Myles Borins) [#3534](https://github.com/nodejs/node/pull/3534)

**Comment by TheAlphaNerd** [comment]
Some commits that didn't land yet
* A number of commits from https://github.com/nodejs/node/pull/1831
   * https://github.com/nodejs/node/pull/3616 relies on this

* [https://github.com/nodejs/node/commit/d8db75730f528cdd0e4629f528c97dc3de0543d6] -  tls: add `options` argument to createSecurePair nodejs/node#2441
  * marked semver-minor 
* [https://github.com/nodejs/node/commit/f6230b9b72e4e25e3177473ea904daf1968470bc] -  test: remove flaky designation from ls-no-sslv3  nodejs/node#3620
  *  fix for a flaky test. I wanted to land this last in case there was a regression and it had to be rolled back
* [https://github.com/nodejs/node/commit/6b0c906e6badbba64611feb766d57b233b64e5f9] -  tls: remove util and calls to util.format nodejs/node#3456
  *  Likely ready to land, was requested it have time to on master first
* All three commits from https://github.com/nodejs/node/pull/3461 - AsyncWrap external API improvements
  * just wanted another person to verify before landing
* [https://github.com/nodejs/node/commit/57bce60da33b26d8e782c92fcd56f7af6ada8c4d] -  child_process: don't fork bomb ourselves from -e nodejs/node#3575
  * It was suggested this spend some time on v5 first.
* two commits from https://github.com/nodejs/node/pull/3636 
  * This missed the LTS watch original, I added the label and was going to land it today if there were no objections
* [https://github.com/nodejs/node/commit/33827e3f6864872f357da6f9566f3c90b138c4ef] -  cluster: remove handles when disconnecting worker  https://github.com/nodejs/node/pull/3677
  *  Ben suggested this wait for it to live on 5.x a bit before landing

Everything else has been on master for a week or less than a week although there are some PR's from that batch that can be considered

* a series of commits by @stefanmb fixing various crypto issues / tests
  * https://github.com/nodejs/node/pull/3755
  * https://github.com/nodejs/node/pull/3756
  * https://github.com/nodejs/node/pull/3758
  * https://github.com/nodejs/node/pull/3759
* A handful of doc fixes that are dead simple to port and don't require testing

Let me know if you want me to follow up on this, if I do land anything I'll chime in the thread so the above list can be updated

**Comment by TheAlphaNerd** [comment]
I'm going to leave this commit open to reference new commits as they land on LTS. @rvagg once it has been added to the above list please feel free to remove it from here.

* [208de5314590c2a56152b39fe05752631bde3ffd] -     doc: document release types in readme https://github.com/nodejs/node/pull/3482

**Comment by Fishrock123** [comment]
Btw, this is **src**:

* [[`935b8be8f6`](https://github.com/nodejs/node/commit/935b8be8f6)] - Add missing va_end before return (Ömer Fadıl Usta) [#3565](https://github.com/nodejs/node/pull/3565)

**Comment by TheAlphaNerd** [comment]
as 4.2.2 has been cut I suggest we close this issue
