### ISSUE TITLE
Next LTS Meeting

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#60]
@nodejs/lts ... Scheduling the LTS meetings this past few weeks has been a bit problematic due to holiday/vacation schedules and conflicts. Next week many of us will be heading to Portland for Interactive on Monday. I propose that we schedule the next LTS meeting for the following week -- Monday December 14th.

**Comment by bnoordhuis** [comment]
Works for me.

**Comment by bnoordhuis** [comment]
Can you send an invite this time so we (well, I) won't forget?

**Comment by jasnell** [comment]
Yes... Especially so that *I* won't forget either ;-)

**Comment by TheAlphaNerd** [comment]
Works for me

**Comment by zkat** [comment]
I'm a maybe for this one, but I'll try.

**Comment by mhdawson** [comment]
+1

**Comment by jasnell** [comment]
Invites sent. I will be posting the agenda over the weekend

**Comment by mhdawson** [comment]
I likely won't make this one after all so don't wait for me.
