### ISSUE TITLE
Discuss the possibility of occasional semver-minor bumps in LTS

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/LTS#61]
Bringing this up due to https://github.com/nodejs/node/pull/3609 and https://github.com/nodejs/node/pull/4135, of which we've assessed the impact to be minimal in risk, but great in potential benefit.

Perhaps we could have occasional minor bumps on LTS lines to include these sorts of features we've carefully selected.

I suggest we do assessments quarterly to see if we should do a minor bump.

**Comment by Fishrock123** [comment]
@nodejs/lts

**Comment by jasnell** [comment]
That sounds reasonable. We should, however, try to establish some kind of rubric for evaluating these things. For instance, changes that improve usability of testing, debugging, support, etc would have preference over changes that simply add new API calls, etc.

**Comment by mhdawson** [comment]
I agree having the rubric will help, I also wonder if they need to be quarterly or "when appropriate"

**Comment by Fishrock123** [comment]
> I agree having the rubric will help, I also wonder if they need to be quarterly or "when appropriate"

We should have some way of stacking them up imo, unlike the stable branch. Just so we don't do like, two in a row for LTS users who may be more on-edge.

**Comment by jasnell** [comment]
Dropping them into the staging branches ought to work. We'll just need to
make sure they don't transfer over to the release branches until we're ready

**Comment by ofrobots** [comment]
+1 on getting this better defined. IMO, it is fine to stage/stack these changes, but the schedule needs to be predictable rather than the limbo that the https://github.com/nodejs/node/pull/3609 is in at the moment.

**Comment by TheAlphaNerd** [comment]
Since we have been doing occasional semver minor bumps is it safe to close this?

**Comment by jasnell** [comment]
Yes
