### ISSUE TITLE
LTS WG Meeting 2015-01-11

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#67]
@nodejs/lts -- we currently have no active LTS agenda items.  If any one feels strongly about having a meeting today, please respond with a few agenda items.

**Comment by TheAlphaNerd** [comment]
Currently tagged issues:

Updating async_wrap in 0.12.x
 * https://github.com/nodejs/node/issues/4592

Currently tagged PR's:

tools: change tick processor install path
 * https://github.com/nodejs/node/pull/4021
 * https://github.com/nodejs/node/pull/3032
 * https://github.com/nodejs/node/pull/4224

Force line-buffering for stderr
 * https://github.com/nodejs/node/pull/3701

Feature/clang format
 * https://github.com/nodejs/node/pull/3612

**Comment by jasnell** [comment]
#3612 was closed, removed the tag.
#4592 likely is never going to make it into v0.12
Everything else seems uncontroversial

**Comment by TheAlphaNerd** [comment]
sgtm
