### ISSUE TITLE
time sensitive request - please review survey questions 

### ISSUE THREAD

**Issue by gtewallace** [nodejs/LTS#69]
Hi everyone,

The Node.js Foundation is conducting a user survey and we'd like your input on the questions related to the versions people use and whether/when they plan to move to v4, if not why not and what resources they need to be successful. We'd love this group's input to ensure the version-related questions are on point.
The survey will go out Thursday 1/14 at 11:30 Eastern, so I need any comments by EOD Pacific tomorrow, Wednesday 1/13.
Here are the version-related questions:

What version of Node.js do you use in production?
- v.10
- v.12
- v4
- v5

(If other than v4) Have you considered moving to v4 ?

- Yes
- No

(if no) Why not (please provide specific concerns or technical barriers, such as lack of migration tools, best practices, satisfaction with current release, etc.)?

(if yes) Do you plan to upgrade to v4?

- Yes
- No

(if no) Why not (please provide specific concerns or technical barriers)?

(if yes) What resources do you need to make your upgrade successful?

(if yes) When do you plan to upgrade?

(if v4) Did you upgrade from a previous version of Node.js? 
- Yes
- No, I started with v4

(if yes) Please describe your upgrade experience - include things like how difficult or easy it was, particular pain points along the way, how you resolved them, the resources you found to be most helpful - documents, videos, people, forums, consultants, etc., how long it took, what your process was.

On a scale of 1-10 where 1 is very confused and 10 is perfectly clear, how would you rate your present understanding of which *version* of Node.js you should be using in production?
Use this space to explain your answer (optional).

What can the Node.js Foundation do to make it more clear which version of Node.js you should be using?

Please provide any additional information that will help the Node.js Foundation increase clarity around versions and make it easier for you to upgrade.

**Comment by mikeal** [comment]
Also /cc @ashleywilliams and @chrisdickinson cause I know they did some
survey's on twitter and may have additional input.

**Comment by Fishrock123** [comment]
cc @nodejs/tsc

**Comment by Fishrock123** [comment]
> What version of Node.js do you use in production?

Add 0.8?

> (If other than v4) Have you considered moving to v4 ?

"if 0.x"? 
We should maybe have a separate question about downgrading from v5 to v4.

> On a scale of 1-10 where 1 is very confused and 10 is perfectly clear, how would you rate your present understanding of which version of Node.js you should be using in production?
Use this space to explain your answer (optional).

Maybe we should just ask some questions here to help determine this? i.e. which versions(s) have lts support?

**Comment by DavidTPate** [comment]
I'm thinking a question about what they upgraded to v4 from would be useful.

(if v4 and upgraded) Which previous version of Node.js did you upgrade from?
* v.8
* v.10
* v.12
* v4
* v5

**Comment by Fishrock123** [comment]
@DavidTPate I agree.

**Comment by mhdawson** [comment]
Do we also want to ask when they upgraded ? I'd e interested in how soon after v4 was available that they upgraded

**Comment by gtewallace** [comment]
thanks all - I'll incorporate these suggestions and others that may come in

**Comment by rvagg** [comment]
Can we please use "v0.10" and "v0.12"? I'm not aware of anyone dropping the `0` in general usage and it has the potential to confuse responders and confuse messaging.

**Comment by Fishrock123** [comment]
Ah I missed that. :/

@gtewallace Yes, we definitely need to mark 0.x version as 0.8, 0.10, 0.12. The leading zero has non-trivial importance.

**Comment by Fishrock123** [comment]
... Was this already sent? The OP said it was to be sent tomorrow.

https://twitter.com/ag_dubs/status/687313480572112896

**Comment by gtewallace** [comment]
hey everyone - yes - it did go out due to a snafu with our email team - apologies for that. All of the input so far has been incorporated.

Also, some have raised the issue of the survey reading "java script" and not JavaScript - this seems to be some sort of weird bug in SurveyMonkey, as strange as that sounds - every time I changed it to JavaScript and hit save, it goes back to java script...
