### ISSUE TITLE
LTS WG Meeting 2016-1-25

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#72]
# When
2016-01-25 @ 01:00 PM Pacific Time 
# Who
@nodejs/lts

# Where

Hangout on Air

Participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYdOS9gwfQEhWpfK11N_AYQ8S3yLtFXfBqzNZAc9AYAbJicOog?hl=en

Observers: http://youtu.be/C9yz0yevpB0 

# Minutes

https://docs.google.com/document/d/1C0xbF4hb-WzYBJrDIyPTJV1p2zgAwxFu61F-kES1CoM/edit

Agenda Issues:

## nodejs/node-v0.x-archive

* Deprecate Array#values() in 0.12.x [#25877](https://github.com/nodejs/node-v0.x-archive/issues/25877)
* Deprecate smalloc in v0.12 [#25784](https://github.com/nodejs/node-v0.x-archive/issues/25784)

### nodejs/node

* Updating async_wrap in 0.12.x [#4592](https://github.com/nodejs/node/issues/4592)

### nodejs/LTS

* Discuss possible clarifications to the LTS messaging / labeling [#63](https://github.com/nodejs/LTS/issues/63)
* Discuss the possibility of occasional semver-minor bumps in LTS [#61](https://github.com/nodejs/LTS/issues/61)
* Schedule for v0.10.x and v0.12.x Releases [#52](https://github.com/nodejs/LTS/issues/52)
* Charter this [#48](https://github.com/nodejs/LTS/issues/48)

**Comment by jasnell** [comment]
I think #63, #61 and #52 are old and can likely be removed. 
I also think nodejs/node#4592 is old also.

One additional item I would add is that we should talk about always having a release candidate process for every RC to avoid the 4.2.5=>4.2.6 type issue again

**Comment by bnoordhuis** [comment]
I'm going to excuse myself, I need to catch up on sleep.

> Deprecate Array#values() in 0.12.x

I'd close this.  I think we put this in the release notes at one time.

> Deprecate smalloc in v0.12

I think a note in smalloc.markdown that it's deprecated and removed in newer versions should be sufficient.  It's at 'Experimental' now; there were no stability guarantees anyway.

> Discuss the possibility of occasional semver-minor bumps in LTS

Seems fine to me.  I thought we'd already agreed on this?

I don't have an opinion on the other issues.

**Comment by mhdawson** [comment]
Minutes added here:

https://github.com/nodejs/LTS/blob/master/doc/meetings/2016-01-25.md

Link to watch the recording: http://youtu.be/C9yz0yevpB0
