### ISSUE TITLE
LTS - Breaking security issues

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#74]
More than a few times we've run into security issues which are "breaking" but are important enough that they need to be back ported to LTS.  The purpose of this issue is to discuss/agree on how we will handle these cases so that we don't need to discuss/decide for each one as they come up.

The starting proposal is (based on discussion with @jasnell) :

* Secure by default.  Even though we try to avoid breaking changes in LTS, it is important that Node is secure by default so when we back port these changes they will be enabled by default.

* When possible we will provide a command line flag to revert a breaking change that has been back ported.  "possible" will depend on where the changes are being made (for example in a dependency) and the performance impact of doing the check for the revert.

* The flags to allow reversion will not be included in master or stable, and as such at each major release boundary the list of reverts for LTS will be reset to none.  This avoids building an ever growing set of possible reversions and ensures at least at major release boundaries users move to the best security stance.

Separately on the implementation side to simplify adding the revert flags we could add a new flag

  --revert=

which takes a list of comma separated names, each name being for a specific back port.  We should be able to come up with an implementation were we have something like an array which defines these names and the bit in integer that represents that back port.  Adding a new revert would then be simply adding the new name to that array and existing code would now add support for that name in the existing --revert= command line option and the existing code would set the bit when the name was present in the list provided.  When back porting the main additional work would then be to add the check of the bit in the existing integer.

**Comment by jasnell** [comment]
Considering the `--revert=` flag... I'm thinking that we limit it strictly to security related issues and print a nice big "Security Warning" on startup whenever it is used. The labels can be the CVE numbers, and if reverting a particular CVE is not supported for a given version we abort with an error. This would need to be *very* carefully managed and we would have to make sure there is very good reason to allow a particular change to be reverted.

**Comment by Fishrock123** [comment]
I agree about the warning; if you are using this kind of thing it should be made very clear what is happening.

These would literally be switches for "but I want my application to have a security vuln so I can use `$hack`".

**Comment by Fishrock123** [comment]
Is there a reason we'd only have this flag in LTS?

It seems to be, the basic functionality should be landed in `master` and then used where necessary. I suspect it will also be useful to have this in Stable branches in case there are breaking security changes across the board.

**Comment by mhdawson** [comment]
Since stable becomes LTS, if we include in stable then we'd have to remove some flags as part of declaring a version LTS.  Rodd mentioned on https://github.com/nodejs/node-private/pull/16#issuecomment-179755747some other reasons it may be ok to leave out of stable

**Comment by mhdawson** [comment]
Based on discussion in last LTS WG meeting I think we are in agreement.  Closing
