### ISSUE TITLE
LTS vs Maintenance

### ISSUE THREAD

**Issue by MystK** [nodejs/LTS#76]
What's the difference between the two?

**Comment by TheAlphaNerd** [comment]
There are both Active + Maintenance LTS

The first 18 months are active, the last 12 are maintenance.

During active we try and backport as much as reasonably possible. During Maintenance we only backport security fixes and major unavoidable bug fixes

**Comment by Lukenickerson** [comment]
> During active we try and backport as much as reasonably possible. During Maintenance we only backport security fixes and major unavoidable bug fixes

While this is explained in the text in https://github.com/nodejs/Release#release-plan it would be good to also include a legend or bulleted list closer to the chart so it's easier to locate the definition of "CURRENT" vs. "ACTIVE" vs. "MAINTENANCE".
