### ISSUE TITLE
LTS WG Meeting 22 Feb 2016

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#77]
# When
Planned for regular time 4 EST 2016-02-22

# Who
@nodejs/lts

# Where

Hangout link for participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYcj6tgrqSVh4q9ze970N3nQMTCLftjz4TNOyQmrD7a4gHGTLw?hl=en&authuser=0

Link for those who just want to watch: http://youtu.be/Bv-ynSxaozA

Event page: https://plus.google.com/events/c1pckqs91mk6nq8q2assijt0728

# Minutes
Google docs link for minutes : https://docs.google.com/document/d/1VZdwPDSY71dZyYOXSZ6EkbycujRzb-rK0n3pUP-ctbA/edit

# Agenda 

* Charter this [#48](https://github.com/nodejs/LTS/issues/48)

**Comment by mhdawson** [comment]
@nodejs/lts just ran the query to see what was labelled lts-agenda and only #48 showed up which I think is old and does not need discussion.

Does anybody have something for the agenda ?

**Comment by bnoordhuis** [comment]
Nothing from me.  Wouldn't mind if we skip it.

**Comment by mhdawson** [comment]
Minutes here https://github.com/nodejs/LTS/blob/master/doc/meetings/2016-02-22.md
