### ISSUE TITLE
Release Candidates - Awareness

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#78]
I'm wondering how people know that RCs are available to test ?  From what I see you need to have the direct link to the directory as I don't see any links from the download pages.

The second question is how people test effectively for native modules as I found the headers were not automatically downloaded and I had to specify the ones for 4.3.1 to test it out.

**Comment by Fishrock123** [comment]
@mikeal is there a way we can get better messaging for RCs on twitter and such?

**Comment by mikeal** [comment]
@Fishrock123 we can use twitter for whatever we want but the feedback we've gotten so far is that our audience has "release announcement fatigue" which is concerning. If people stop paying attention to these announcements it makes it harder to get people to use significant and critical updates.

Who is the audience for LTS RC's? If it's a handful of enterprises we'd like to see try these out before they go live then twitter is a terrible medium to reach them.

**Comment by TheAlphaNerd** [comment]
I've been individually reaching out to colleagues I know are using LTS in production. Perhaps an opt-in RC mailing list could be a good solution/

**Comment by mikeal** [comment]
@TheAlphaNerd we could create a locked "announcement only" issue for this in LTS as well.

**Comment by mikeal** [comment]
Random thought: why don't we create an `announcements` repo where we create locked threads for each announcement the foundation is doing? We could have one for Express and one for LTS RCs.

Thoughts?

**Comment by mhdawson** [comment]
@mikeal that sounds good to me.  People who are interested can watch the repo (or unwatch easily if they are no longer interested)

**Comment by TheAlphaNerd** [comment]
I'm going to close this for now. @mhdawson please feel free to reopen to continue discussion.

I believe @ljharb was close to getting rc support into nvm

**Comment by ljharb** [comment]
Relatively close :-)
