### ISSUE TITLE
Confusing version number v4.2.0

### ISSUE THREAD

**Issue by robations** [nodejs/LTS#79]
Hello, I feel like the version number that is referred to as LTS is a little confusing. There are multiple references to v4.2.0 as being LTS, whereas, as far as I can tell from diagrams etc., the LTS applies to all releases >= 4.2.0, < 5? If I'm deploying to v4.3.x I want to be absolutely sure it has LTS.

For example, in the release table in `README.md` it lists releases 0.10 and 0.12 which for 0.x under semver are equivalent to major releases, and then 4.2.0 which would be a patch release.

**Comment by bnoordhuis** [comment]
> the LTS applies to all releases >= 4.2.0, < 5?

That's correct.  The latest v4.x release is the latest LTS release.

**Comment by robations** [comment]
@bnoordhuis thanks for the clarification.

I think the wording or terminology could be improved. From the grammar (verb tense), the document looks like it was written at a point in time, but there is a link to this repo from the home page of nodejs.org, so I would assume it to be be a working document. If you actually agree with my point I could provide a PR with suggestions.

**Comment by bnoordhuis** [comment]
@robations I'd be happy to review a pull request.

**Comment by Fishrock123** [comment]
@robations There is a handy page here which shows which released versions are LTS: https://nodejs.org/en/download/releases/
