### ISSUE TITLE
Mention of PPC LE missing in news

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#81]
It was pointed out to me that we were missing the mention for PPC LE here: https://nodejs.org/en/blog/release/v4.3.2/

I think I saw an issue from @rvagg to add PPC LE to release templates, but I don't see any open issues like that now.

It was included for 5.7.1: https://nodejs.org/en/blog/release/v5.7.1/  but we may have different templates for 5.X from 4.X 

@TheAlphaNerd

**Comment by TheAlphaNerd** [comment]
https://github.com/nodejs/nodejs.org/pull/555

4.3.2 release post is updated. the change @rvagg made has landed but I didn't sync with upstream prior to generating the blog post. I have regenerated it and merged it into the repo, we should see the update soon.

As the script is there and I am now synced we should not see this happen again
