### ISSUE TITLE
proposal: expedite v0.12 into maintenance mode

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/LTS#82]
We clearly do not have the resources to maintain 0.12 as if it were in active LTS (ala v4). 

Let's just make the cut to it being in maintenance mode and stop pretending like it isn't for both ourselves & our users.

**Comment by bnoordhuis** [comment]
I thought maintenance starts on April 1st of this year?

**Comment by Fishrock123** [comment]
Hmmm, I'm not sure, I thought it was in october of this year.

**Comment by mhdawson** [comment]
I don't think its worth changing the messaging since its less than 1 month from now.
