### ISSUE TITLE
Discussion: Consider merging "LTS" and "Maintenance" into simply "LTS"

### ISSUE THREAD

**Issue by rvagg** [nodejs/LTS#84]
It's likely that our entire LTS + Maintenance period for any release line is going to look something like this regardless of what we call the phases:
- Initial phase where codebase is close to current Stable release line: easy cherry-pickings, lots of activity, relatively frequent releases—v4 is still in this honeymoon period
- Middle phase where the codebase diverges somewhat, helped on by additional semver-major shifts in Stable release lines, cherry-picking becomes more difficult, releases slow down a little
- Overlapping LTS phase where we have another LTS line starting to take prominence, v6 will begin this for us in October, users will shift, our own attentions will shift and it'll become increasingly difficult to maintain an older LTS line simply because it isn't a priority for contributors working on it—I'm guessing that the certainty of our LTS plan won't make this quite as bad as the 0.10 and 0.12 divergence where almost nobody working on core cares about them now yet they are heavily used out there. The business interests of companies contributing to core will have reason to still care because of heavier investment in v4 strategies.
- Dying LTS phase where we are just waiting for it to end and for people to move off it, this will be roughly our Maintenance period, hopefully not a full 12 months, maybe closer to 8 or 6, like what 0.10 is starting to do now.

The point of that description is to suggest that our categorisation of LTS and Maintenance are disconnected from how we (will) actually manage the LTS release lines. Our concerns will be more about increasing difficulty of maintenance, shifting to being concerned because we are connected into business concerns that need to keep them going, then shifting even further into life-support where it's really hard to care. You just need to look at both 0.10 and 0.12 for this, 0.12 in particular is a little bit shocking in the way that we have pretty much all given up on it, it's no less "Maintenance" than 0.10 is now so the differences are artificial.

Another pro for removing "Maintenance" is a simplification of what has proven to be very difficult to communicate (and continues to be!). Check out what it would look like:

![nodesource_lts_diagram_sans_maintenance](https://cloud.githubusercontent.com/assets/495647/13602322/2866e19c-e58a-11e5-945a-f443c69f4ece.png)

On the con side for removing "Maintenance" I see a few issues:
- It's a signal about how little we're going to be touching that release line during that period, don't expect anything major going in here, it's down to security releases and major flaws only
- It's a signal to users that it's a time to upgrade, we've moved beyond pretending to care too much and it's been plugged into life support, not a good bet to pin your production strategy to (an ideal time for AWS Lambda to move on for example!)
- It's a mechanism by which we use to accept or reject change proposals to release line branches. We can say "sorry, we're not touching that at all, we're in Maintenance and have a commitment to keep the changes to security and major bugs only".

_Discuss_

**Comment by mhdawson** [comment]
We could refer to the full period as LTS, but qualify as to whether it is 'Active' or 'Maintenance', with the switchover likely being when the newer release goes into LTS.   This could be presented using the picture you have above, but then lower down in the README include an expansion of a typical LTS cycle where we show the breakdown between the Active and Maintenance portions along with the reasons you described explaining why it transitions from Active to Maintenance over time and the expectations in terms of what changes go in in the 2 sub-phases.  One advantage of this might be that we can claim we are not "changing" the plan, just refining the explanation to make it clearer.

I'm not sure I'd say we don't care about 0.12.X, its just that we are letting what we care about be driven by demand as opposed to trying to pull as many of the changes back as possible.

**Comment by mikeal** [comment]
I'm all for simplifying this messaging. However, we do need some way of exposing the difference between "we care less about this and will only ship critical fixes" and "we no longer have the ability to ensure critical fixes." 

In the AWS Lambda case, this new timeline would suggest to them that they are fine until October and then they will only get critical fixes (which might be fine with them). It doesn't convey that OpenSSL is cutting support for this line and we will no longer have the ability to ship critical security updates.

**Comment by Fishrock123** [comment]
I prefer to keep maintenance. There is a point where we can't really support something any more except for security fixes. For something is later-stage LTS we might not do something ourselves, but we would probably accept someone's patch to backport something. With maintenance that won't happen. It's past that point, time to move on unless it's for security.

**Comment by TheAlphaNerd** [comment]
I'm +1 on keeping maintenance. @rvagg are you comfortable closing this?

**Comment by rvagg** [comment]
yep
