### ISSUE TITLE
Track backporting AsyncWrap changes

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/LTS#86]
There are quite a few commits that need to land to get LTS up to snuff for async wrap. Let's use this issue to track those and make sure we don't miss anything (especially fixes for regressions)

src: fix MakeCallback error handling  https://github.com/nodejs/node/pull/4507
http_parser: use `MakeCallback` https://github.com/nodejs/node/pull/5419
src,http: fix uncaughtException miss in http https://github.com/nodejs/node/pull/5591
async_wrap: add uid argument to all asyncWrap hooks https://github.com/nodejs/node/pull/4600

**Comment by TheAlphaNerd** [comment]
We will also need to include https://github.com/nodejs/node/commit/b72dbdbe430ef83c73cf535bc0dabdba2a64b352 from https://github.com/nodejs/node/pull/5233

**Comment by trevnorris** [comment]
Include https://github.com/nodejs/node/pull/5756

**Comment by AndreasMadsen** [comment]
https://github.com/nodejs/node/pull/5756 has landed, can we do this now? As you can see from the issue references, I'm getting a few issues about the lack of/poor support for Node v4.

**Comment by TheAlphaNerd** [comment]
These have landed
