### ISSUE TITLE
Support from V8 for Node's LTS releases

### ISSUE THREAD

**Issue by natorion** [nodejs/LTS#88]
The V8 team is wondering how we can support Node's work for LTS releases.  After some preliminary discussions we were thinking about the following topics:

# Reconcile security bug process
Node is already getting pre-access to V8 related security bugs. In this case CVEs are issued by Chrome. The CVEs issued by Node are currently 'off the radar'.
etc...

# Help maintaining backports
Make it easier for Node to identify needed backports.
etc...

# Handling patches on V8's deprecated branches upstream
Floating patches can land on deprecated branches and some tests are run.
etc...

We think it makes sense to discuss this topic in more detail in one of the upcoming LTS WG meetings.

**Comment by TheAlphaNerd** [comment]
closing in lieu of #111
