### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/LTS#92]
Currently our release schedule is somewhat haphazard. We for the most part attempt to release every week, but occasionally release every other week. We also don't have a set release schedule for RC's.

This came up in a discussion with @mhdawson, specifically about how we can make our release timing more reliable.

I'm adding the lts-agenda tag so we can discuss this in our next meeting

**Comment by mhdawson** [comment]
From discussion in last LTS meeting:

Likely to have less changes going in with the release of 6.X
Plan for monthly release, last week of each month, unless not enough change to warrant it
Of course security releases may result in unplanned release before then

**Comment by TheAlphaNerd** [comment]
closing for now
