### ISSUE TITLE
Nightly and/or RC builds for LTS patch releases

### ISSUE THREAD

**Issue by jfhbrook** [nodejs/LTS#93]
Hey all,

I have an interesting use case for what I'll call "preview" builds of LTS.

Basically: We're running LTS in production, and we ran into a [fairly serious bug that was crashing our apps](https://github.com/nodejs/node/pull/6164). Because of LTS lag time, the patch won't actually be available in an LTS release for some time (a week? two weeks?).

In the interest of allowing us to test out the patch, Myles did a test build and threw it onto /test and I was able to install from there. But that seems like a pretty ad-hoc way of getting access to builds of LTS staging.

(I should say here that, yes, we can and did float the patch against 4.4.2 ourselves.)

Eventually, I discovered /nightly and /rc but also discovered that you just straight up don't do nightlies or rcs for LTS releases! I know that on a certain level it doesn't seem to make sense because LTS is only getting patch releases and, given the current workflow, the patches tend to land all at once after being vetted in v5. That said, given my use case of wanting to take advantage of unvetted patches against v4 without doing custom builds myself, I'd find LTS previews helpful.

Thanks!

**Comment by TheAlphaNerd** [comment]
We are now officially doing an r.c. process. Please let me know if you think there is a better way we could be informing people about it.
