### ISSUE TITLE
2016-04-18 - No LTS Meeting Today

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#94]
Sorry for the late notice, but given a few conflicts on my end and given that it appears we don't have any pending LTS issues, let's not have an LTS meeting today. @nodejs/lts ... unless there's an issue we need resolution on that I'm missing.

**Comment by TheAlphaNerd** [comment]
There is a pending issue resolved back porting libuv but it is a minor and
not time sensitive

**Comment by mhdawson** [comment]
Closing as we are past the date, and there was a meeting this week
